### ISSUE TITLE
When I use youki, got an error of "/proc/timer_stats" not exist AND youki did not terminate successfully: exit status 1 in docker and containerd

### ISSUE THREAD

**Issue by zzyyzte** [containers/youki#1105]
Description

1. When I use youki to create a container, I got an error of "[WARN crates/libcontainer/src/process/container_init_process.rs:90] 2022-08-05T07:09:54.215862570+00:00 masked path "/proc/timer_stats" not exist"  AND  "Error: failed to create container"
2. When I use youki in docker, I got an error of "docker: Error response from daemon: failed to create shim: OCI runtime create failed: /usr/local/bin/youki did not terminate successfully: exit status 1: Error: failed to create container"
3. When I use youki in container, I got an error of "FATA[0001] failed to create shim: OCI runtime create failed: youki did not terminate successfully: exit status 1: unknown"

Steps to reproduce the issue:
use youki only
```
$ mkdir -p tutorial/rootfs
$ cd tutorial
$ docker export $(docker create busybox) | tar -C rootfs -xvf -
```

use youki in docker
```
$ dockerd --experimental --add-runtime="youki=$(pwd)/target/x86_64-unknown-linux-gnu/debug/youki"
$ docker run -it --rm --runtime youki busybox
```

use youki in containerd
/etc/container/config.toml
```
version = 2
[plugins."io.containerd.runtime.v1.linux"]
  shim_debug = true
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.youki]
  runtime_type = "io.containerd.runc.v2"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.youki.options]
    BinaryName = "/usr/local/bin/youki"
```
`nerdctl -n k8s.io run --runtime youki -d --name testa$j docker.io/library/busybox:1.28 sh`

env:
```
uname -r
4.18.0-193.14.2.el8_2.x86_64
rpm -qa | grep docker
docker-ce-rootless-extras-20.10.14-3.el8.x86_64
docker-ce-cli-20.10.14-3.el8.x86_64
docker-ce-20.10.14-3.el8.x86_64
rpm -qa | grep containerd
containerd.io-1.5.11-3.1.el8.x86_64
```

**Comment by Furisto** [comment]
Hi @zzyyzte we currently require a kernel >= 5.4.

**Comment by utam0k** [comment]
@zzyyzte Please feel free to reopen if there is another issue.
