### ISSUE TITLE
CNCF TAG-Runtime Discussion/Presentation? 

### ISSUE THREAD

**Issue by raravena80** [containers/youki#12]
Hello youki team,

I'm one of the co-chairs of the CNCF SIG-Runtime, I'm reaching out and think it would be great for you to present/discuss the project at one of our meetings. An overview of the project would be great.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by utam0k** [comment]
@raravena80 
I'm sorry for the late reply. I contacted you via email. Please look at it.

**Comment by Furisto** [comment]
If @yihuaf wants to do the presentation, it is fine with me. I can join the call if I have time and would be available for questions.

**Comment by utam0k** [comment]
@raravena80 @Furisto @yihuaf Thank you for your cooperation. Let's continue to communicate on this issue. I'll join the meeting when I have time.

@raravena80 What should we do next?

**Comment by utam0k** [comment]
NP. I think I can participate.

**Comment by yihuaf** [comment]
> Sorry folks, I messed up. Will Thursday Nov 4th at 8am PT work? I realized that Nov 2nd is a Tuesday and our meetings are on Thursday. Thx.

Nov. 4th works for me.

**Comment by utam0k** [comment]
@yihuaf @raravena80 @Furisto Thanks!
