### ISSUE TITLE
Support `domainname`

### ISSUE THREAD

**Issue by utam0k** [containers/youki#1213]
https://github.com/opencontainers/runtime-spec/pull/1156

runc: https://github.com/opencontainers/runc/pull/3600

# Goal

- [ ] Implement
- [ ] Add a test for it

**Comment by higuruchi** [comment]
Hi @utam0k ,
May I take this challenge?

**Comment by utam0k** [comment]
@higuruchi Sure!

**Comment by YJDoc2** [comment]
@utam0k I think #1214 completed this?

**Comment by utam0k** [comment]
@YJDoc2 True
