### ISSUE TITLE
containerd: TestContainerKillInitPidHost

### ISSUE THREAD

**Issue by utam0k** [containers/youki#1225]
This issue is a part of [supporting containerd](https://github.com/containers/youki/issues/531)
```console
    container_linux_test.go:1552: killing init didn't kill all its children:
            PID TTY      STAT   TIME COMMAND
              1 ?        Ss     0:01 /sbin/init =
              2 ?        S      0:00 [kthreadd]
              3 ?        I<     0:00 [rcu_gp]
              4 ?        I<     0:00 [rcu_par_gp]
...
```

**Comment by YJDoc2** [comment]
This might get partial support in #1204 
When done, it should implement support for killing all process of a container's cgroup, then we might need to check again if this still fails, and see the reason.
We can try running tests against that PR's branch, but not sure how much complete it is, as still in draft

**Comment by utam0k** [comment]
@YJDoc2 maybe yes...
