### ISSUE TITLE
Suppport wasm workloads using wasmtime 

### ISSUE THREAD

**Issue by Jeffwan** [containers/youki#1278]
We use wasmtime as the webassembly runtime and I would be interested to support wasmtime supported in youki since they are both rust stack.  I notice wasmr has been added in the youki and I would like to extend in a similar to support wasmtime.

I am actually a beginner of rust and I would like to contribute this part including tests and reports

**Comment by utam0k** [comment]
Hi, @Jeffwan. I'm a beginner at wasm, so please tell me what advantage we support `wasmtime`.

**Comment by Jeffwan** [comment]
@utam0k you mean the advantage of `wasmtime` over `wasmr`?

**Comment by utam0k** [comment]
@Jeffwan I  want to know what benefit we archive with this issue.

**Comment by Mossaka** [comment]
(Disclaimer, I am a maintainer [runwasi](https://github.com/deislabs/runwasi), which supports running wasm/wasi workloads using wasmtime and other runtimes)

Let me add one benefit of enabling wasm workloads in the container ecosystem. Wasm/wasi is a lightweight, portable and secure binary format that enables devleopers to build server-side applicaitons in Rust, C++, Go and other languages. One major benefit of enabling wasm workloads is to support function-as-a-service model where a bursty function quickly starts executing and then finishes and dies. If container runtime integrates with a wasm runtime, the function application does not need to bundle a runtime in the image. This significantly reduces the size of the image and allows the container runtime to be shared among multiple wasm modules.
