### ISSUE TITLE
impl: hooks

### ISSUE THREAD

**Issue by drahnr** [containers/youki#13]
Hooks are a vital aspect when mapping complex input devices i.e. gpu or accelerator devices into the container namespace. The most common use case is using machine learning workloads in a container workload that requires cuda access i.e. for CI jobs of [juice](https://github.com/spearow/juice)

Spec ref: https://github.com/opencontainers/runtime-spec/blob/master/config.md#posix-platform-hooks

**Comment by drahnr** [comment]
@utam0k please assign me for this issue, I lack permissions to do so

**Comment by utam0k** [comment]
@drahnr 
I assigned it to you and look forward to your PR.

**Comment by utam0k** [comment]
@drahnr Hi! Do you have any problems? I don't want to rush you, but if there is anthing I can do to help you, I would be happy.

**Comment by drahnr** [comment]
It's been a incredibly busy month, I simply didn't get around to it

**Comment by utam0k** [comment]
I understand. No problem at all. I was just wondering if I should wait for this or not since I'm thinking of doing the first release soon.

**Comment by drahnr** [comment]
If you want to slate a release, go for it! My current plan is to tackle it within the next 3 weeks, but schedules tend to shift quickly

**Comment by utam0k** [comment]
@drahnr Of course I don't mean to burden you. I was thinking of making some adjustments if you are almost ready. I hope you can process at your own pace, without being overwhelmed.
BTW, thanks to the help of many developers, the code and function have increased considerably since the beginning, so please take a look :)

**Comment by drahnr** [comment]
Not a burden at all, just the finite amount of time

**Comment by yihuaf** [comment]
@drahnr Is it OK if I take this issue? I am planning to work on this next :)

**Comment by drahnr** [comment]
@yihuaf go for it! I just started to chip away on my personal backlog 🙃

**Comment by utam0k** [comment]
@drahnr I am sure that your knowledge of railcar will be useful for youki. If you can spare some time, please come back and give us your opinion.
