### ISSUE TITLE
Error[E0599] : no method named `get_notify_fd` found for struct `ScmpFilterContext` in the current scope.

### ISSUE THREAD

**Issue by 92hackers** [containers/youki#1318]
When running command: `make build` and later, when compiling libcontainer v0.0.3.

Repo git hash: 184c21b79485ece170d1ee9da52eaf9ec745ce61

OS kernel: 5.15.0-47-generic  
OS:  x86-64, ubuntu 22.04

**Comment by YJDoc2** [comment]
Hey @92hackers , can you try running `make clean` and re-run `make build`? I tried building both main branch at current commit and the commit you have mentioned, and both seem to build fine without any errors.

It might be possible that some existing dependency of old version of libseccomp might be giving error , as I also remember getting a similar error in past. Unfortunately I don't remember what was the root issue, and how I solved it :sweat_smile: 

Can you try cleaning and rebuilding as I mentioned above and let us know if the error is still there? 
Thanks

**Comment by utam0k** [comment]
@92hackers May I ask you to make sure that you can compile runc without errors in your env?

**Comment by 92hackers** [comment]
@utam0k , you are right.

After i installed `libseccomp-dev` on my ubuntu, then i can build `youki` successfully, with libcontainer `v0.0.3`。

Thanks.

**Comment by utam0k** [comment]
@92hackers I'm glad to help you

**Comment by ms140569** [comment]
I have the very same error on a pretty old ubuntu (18.04.6 LTS) using libseccomp-dev 2.5.1

What is the minimal version of libseccomp-dev needed?

**Comment by YJDoc2** [comment]
@ms140569 libseccomp-dev 2.5+ should work, can you once try cleaning and re-compiling? (Even though that should not be a reason for error)

**Comment by ms140569** [comment]
@YJDoc2 although I did a separate make clean and then a make youki-dev before which showed this error I've now done it in one go which solved the issue:

make clean && make youki-dev

I have no idea why this now works. I've doublechecked my command-history to make sure that I really did a make clean and nothing relevant in between ...  I will now do it again and again to verify ...

**Comment by flokli** [comment]
I also ran into this compilation failure, in my case it was due to libseccomp not being available in my dev environment / accessible by pkg-config. After making it available, it compiled successfully.

**Comment by flokli** [comment]
I did some more digging.

In `build.rs`, the `libseccomp` crate discovers via pkg-config if it can find the libseccomp-dev, and then sets cfg libseccomp_v2_5.

`libseccomp/lib.rs` only imports the `notify` mod on `#[cfg(any(libseccomp_v2_5,doc))]` in `libseccomp/lib.rs`,
so during *build-time* of libseccomp crate, libseccomp-dev needs to be available.

**Comment by utam0k** [comment]
@flokli Thanks for your investigation. Do you know how to avoid this error?

**Comment by flokli** [comment]
I guess this project is making use of the functionality, and it already documents it needs to be installed. Not sure what else to do.
