### ISSUE TITLE
Upgrade wasmer to v3.0

### ISSUE THREAD

**Issue by utam0k** [containers/youki#1372]

**Comment by chermehdi** [comment]
What's the goal here? is it just to bump a version and make sure that tests still pass?

**Comment by utam0k** [comment]
> What's the goal here? is it just to bump a version and make sure that tests still pass?

@chermehdi 
Thanks for your comment. That's right. Do you have interested it?

**Comment by chermehdi** [comment]
sure I can take it 👍
