### ISSUE TITLE
implementation of masked paths

### ISSUE THREAD

**Issue by humancalico** [containers/youki#140]
ref: https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#masked-paths

**Comment by yihuaf** [comment]
@humancalico Have you started this yet? Let me know if I can help.

**Comment by humancalico** [comment]
@yihuaf Hey sorry I wasn't able to find the time to get started. I'll ping you if I get stuck on anything.

**Comment by humancalico** [comment]
Hey @utam0k @yihuaf could it be that this might be already implemented? I tried uncommenting https://github.com/containers/youki/blob/6dfad07c024bb93b202cdc96fb37e6db5aa6c98b/integration_test.sh#L40 and running the `integration_test.sh` script and it seems like the tests are running fine. Could you verify this?

**Comment by yihuaf** [comment]
Test is not running OK for me:
```
not ok 1 - check masked paths
```

**Comment by chenyukang** [comment]
This is duplicated with #227 .

**Comment by chenyukang** [comment]
> @yihuaf Hey sorry I wasn't able to find the time to get started. I'll ping you if I get stuck on anything.

Sorry, I didn't notice you are working on it.
