### ISSUE TITLE
implementation of readonly paths

### ISSUE THREAD

**Issue by utam0k** [containers/youki#144]
ref: https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#readonly-paths

**Comment by utam0k** [comment]
@duduainankai 
Are you interested?

**Comment by duduainankai** [comment]
Yeah, I will have a try. Thank you.

/assign

**Comment by yihuaf** [comment]
@duduainankai Have you started this yet? Let me know if I can help.

**Comment by duduainankai** [comment]
@yihuaf  Yeah, I am already working on it. Thanks.
