### ISSUE TITLE
implementation of ps command

### ISSUE THREAD

**Issue by utam0k** [containers/youki#146]
ref: https://github.com/opencontainers/runc/blob/master/man/runc-ps.8.md

**Comment by zidoshare** [comment]
I can take it on.

**Comment by fbrv** [comment]
I haven't noticed that @zidoshare has taken the issue. I made some experiments and it should be pretty easy to implement, retrieving the container cgroup folder, iterate over it, and on file "cgroup.procs" read the content and show the array, should be enough.
If you have any questions I can help you with this issue

**Comment by utam0k** [comment]
@zidoshare Have you already started development?

**Comment by zidoshare** [comment]
> @zidoshare Have you already started development?

sorry, I am busy with work. And I will finish this week.

@fbrv , I see that the state.json file of runc contains a devecies field, but I don’t see similar content in youki. So I am not sure if I need to scan cgroups folder by myself.

**Comment by zidoshare** [comment]
I don’t have enough experience that I may not be able to start work too quickly. sorry,sorry.

If you are eager to achieve it, you can assign it to others. So sorry about that.

**Comment by utam0k** [comment]
No problem. If you haven't gotten around to it yet, why don't you give this issue to @fbrv and try something else? It looks like we have one cgroup v1 controller response open.
> sorry, I am busy with work. And I will finish this week.

**Comment by zidoshare** [comment]
@utam0k 
In fact, I only have some questions about scanning the cgroups folder. The other development is basically completed. But I may not have time in the last two days, so you can arrange it for @fbrv . I will try to provide some help.

@fbrv 
Have you referenced the implementation of runc?

**Comment by utam0k** [comment]
We aren't in a hurry for this, so please have @zidoshare be the main implementer. I think it would be great if we can cooperate with @fbrv.
> In fact, I only have some questions about scanning the cgroups folder. The other development is basically completed. But I may not have time in the last two days, so you can arrange it for @fbrv . I will try to provide some help.

@fbrv 
If you're interested, I can prepare another issue for you, what do you think?

**Comment by fbrv** [comment]
Yes, sure @utam0k I'm trying to apply what I learn of rust and at the same time I'm learning cgroup, any issue or contribution that potentially can help to understand better these two technologies is more than appreciated. Meanwhile, I could help, if necessary, @zidoshare on is fork on implementing or understand better how to retrieve the root folder and iterate over it

**Comment by utam0k** [comment]
@fbrv 
I have a good task available, so I'll send a mention to you.
> Yes, sure @utam0k I'm trying to apply what I learn of rust and at the same time I'm learning cgroup, any issue or contribution that potentially can help to understand better these two technologies is more than appreciated. 

I'd love to have this one :)
> Meanwhile, I could help, if necessary, @zidoshare on is fork on implementing or understand better how to retrieve the root folder and iterate over it
