### ISSUE TITLE
Fix libcgroups/examples/bpf.rs

### ISSUE THREAD

**Issue by krisnova** [containers/youki#1499]
In #1483 we discovered `bpf.rs` fails clippy check.

```
cargo clippy --all-targets --all-features -- -D warnings
```

## How to reproduce

Please add the example back to `libcgroups/Cargo.toml` and address clippy errors from example.

```diff
diff --git a/crates/libcgroups/Cargo.toml b/crates/libcgroups/Cargo.toml
index 3f91762d..b3e20a78 100644
--- a/crates/libcgroups/Cargo.toml
+++ b/crates/libcgroups/Cargo.toml
@@ -9,7 +9,7 @@ readme = "README.md"
 authors = ["youki team"]
 edition = "2021"
 rust-version = "1.58.1"
-autoexamples = false
+autoexamples = true
 keywords = ["youki", "container", "cgroups"]

 [features]
 ```

and run
```console
$ cargo clippy --all-targets --all-features -- -D warnings
```

**Comment by YJDoc2** [comment]
Hey, I checked with main branch and this does not fail. If this was introduced in #1483 , we should try to resolve it in that, instead of creating an issue.
However, I did find 
```
error: useless conversion to the same type: `u32`
   --> crates/libcontainer/src/syscall/linux.rs:377:44
    |
377 |         let res = unsafe { libc::setrlimit((rlimit.typ() as u32).try_into().unwrap(), rlim) };
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider removing `.try_into()`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_conversion
    = note: `-D clippy::useless-conversion` implied by `-D warnings`

error: could not compile `libcontainer` due to previous error
```
Can someone else validate this?

**Comment by yihuaf** [comment]
I don't see this line and the commit is 17 months ago. I see:

```
 let res = unsafe { libc::setrlimit(rlimit.typ() as u32, rlim) };
```

**Comment by yihuaf** [comment]
I can also confirm that on main branch today, the clippy passes the check.

**Comment by utam0k** [comment]
> I can also confirm that on main branch today, the clippy passes the check.

What version did you use?

**Comment by yihuaf** [comment]
> > I can also confirm that on main branch today, the clippy passes the check.
> 
> What version did you use?

```
$ cargo clippy --version
clippy 0.1.67 (fc594f1 2023-01-24)
```

**Comment by yihuaf** [comment]
I did not get this error. On my dev box, I don't see this error, so I suspect we can close this issue until it pops up again.
