### ISSUE TITLE
Question on youki performance benchmark

### ISSUE THREAD

**Issue by Jeffwan** [containers/youki#1515]
![image](https://user-images.githubusercontent.com/4739316/215020431-ffe0c9e6-504c-483d-b2d4-9d51a0d1ce53.png)

```
$ hyperfine --prepare 'sudo sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' --warmup 10 --min-runs 100 'sudo ./youki create -b tutorial a && sudo ./youki start a && sudo ./youki delete -f a'
```

1. What's the crun and runc commands? it's just basic command without any arguments like below or something else?

```
cd $PATH_TO/rootfs
runc create container_id
runc start container_id
runc delete container_id
```

2. "youki has the potential to be faster and use less memory than runc,"

 I think the number already prove that youki is faster. did you check memory usage for different OCI runtimes?

**Comment by utam0k** [comment]
Hi, @Jeffwan :wave: 
Thanks for your interest.

I think there are two kinds of memory utilization. Which is it?
* Amount of memory used when starting container
* Amount of memory used by the application when the container is running
> I think the number already prove that youki is faster. did you check memory usage for different OCI runtimes?

**Comment by Jeffwan** [comment]
@utam0k 

> Amount of memory used when starting container
I think this is something runtime should care about. I actually copy "youki has the potential to be faster and use less memory than runc," from README.md and I mean "use less memory" means the memory used when starting container.

> Amount of memory used by the application when the container is running
What I understand is application resource utilization would be very similar no matter which runtime spawns it.

**Comment by Jeffwan** [comment]
I change runc command to below but met some problems.

```
$ hyperfine --prepare 'sudo sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' --warmup 10 --min-runs 100 'runc create container_id && runc start container_id && runc kill container_id && runc delete container_id' --show-output
```

`ERRO[0000] cannot delete container container_id that is not stopped: running`

Even I add `runc kill container_id` process, it's an async operation can delete won't work. Do you remember how did you test it?

**Comment by utam0k** [comment]
@Jeffwan Sorry but I am super busy now because of laid off 😭
I will be back after a couple of week.

**Comment by utam0k** [comment]
@containers/youki-maintainers Hi, team. May I ask you to get your help?

**Comment by YJDoc2** [comment]
@utam0k , so sorry to hear that :broken_heart: . I'll try my best to work on this.

@Jeffwan , I tried running the command 
```
$ hyperfine --prepare 'sudo sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' --warmup 10 --min-runs 100 'sudo ./youki create -b tutorial a && sudo ./youki start a && sudo ./youki delete -f a'
```
And for runc simply replaced `./youki` with `runc` , and it worked without any errors. Can you try that?

>I think this is something runtime should care about. I actually copy "youki has the potential to be faster and use less memory than runc," from README.md and I mean "use less memory" means the memory used when starting container.

I agree that we should provide some measurements regarding to memory usage. Do you have any idea how we can measure that exactly? One way I can think of is to see maximum resident set size for each runtime, and compare. But I'm not sure if that would be a valid measurement, as it only indicates peak and not overall.

**Comment by Jeffwan** [comment]
@YJDoc2 I think the scripts works for me now. BTW, I found an interesting project to test the performance and it provides some flexibility to extend to other runtimes. I will put some efforts recently to add youki driver. That it already have some auxiliary tools to measure the resource utilization. I think that would be easier to generate the report.

**Comment by Jeffwan** [comment]
Once I have some progress on the integration, I will create a new issue to track it. The existing problem has been solved and I will close this issue. Thanks!

**Comment by utam0k** [comment]
@Jeffwan I'm interested in your effort. I'm looking forward to your contribution 😍
