### ISSUE TITLE
Support `SCHED_IDLE`

### ISSUE THREAD

**Issue by utam0k** [containers/youki#1533]
https://github.com/opencontainers/runc/pull/3377
https://github.com/opencontainers/runtime-spec/pull/1136

**Comment by lengrongfu** [comment]
Hi, this feature whether having finish?
https://github.com/containers/youki/blob/ab60bfc7e1fc5847b9b164812233ead012692279/crates/libcgroups/src/v2/cpu.rs#L103

**Comment by utam0k** [comment]
@lengrongfu :100:
