### ISSUE TITLE
Build test error:  expected `u8`, found `i8` for bpf

### ISSUE THREAD

**Issue by sou-chon** [containers/youki#1579]
Hi I am trying to run `make unittest` and `make featuretest` but I am getting the following errors

<img width="895" alt="Screenshot 2023-02-16 at 15 56 54" src="https://user-images.githubusercontent.com/35537528/219419706-248ee29c-4480-47ad-872d-4470d306f28f.png">

**Comment by YJDoc2** [comment]
Hey @sou-chon , can you share the details of the system you are building youki on? I tried running these on my system, and they seem to work without any error. Thanks :)

**Comment by kemkemG0** [comment]
I just made a PR #1792 that seems to be related.

**Comment by utam0k** [comment]
If you haven't resolved this issue yet, @sou-chon, please don't hesitate to reopen it.

**Comment by utam0k** [comment]
Thanks, @kemkemG0 💯
