### ISSUE TITLE
Add container ID validation

### ISSUE THREAD

**Issue by lengrongfu** [containers/youki#1580]
Current `youki` not container ID validate, but `runc` is having, https://github.com/opencontainers/runc/blob/537645fd52e97e1e33f3b6b8d71397affada9779/libcontainer/factory_linux.go#L278
Can I add this logic for `youki`?

**Comment by YJDoc2** [comment]
Hey @lengrongfu , can you give a bit more info on where this function will be used? For example, right now we validate the id to be non-zero length in the cli parsing. Similarly, where would these validation be used?

**Comment by lengrongfu** [comment]
We can add a logic to call `validateID` in `build()` and verify whether the container id is valid.

**Comment by YJDoc2** [comment]
Ok, I guess that will help us keep compatibility with runc...
I'm not particularly happy with the fact that the format of ID is not formally defined (as per the code you linked states), which means we are essentially following runc , and taking their choices as is it.

That said, we are trying to be compatible with other runtimes, so it would be a good idea to validate id to be "correct" as per them.

Sure, you can go ahead and open a PR for this, thanks a lot for pointing this out, and showing interest in adding the change :)
