### ISSUE TITLE
implementation of run command

### ISSUE THREAD

**Issue by zidoshare** [containers/youki#159]
ref: https://github.com/opencontainers/runc/blob/master/man/runc-run.8.md

```shell
❯ ls
config.json  rootfs
❯ sudo ~/crun run mycontainer
❯ ~/youki run mycontainer
error: Found argument 'run' which wasn't expected, or isn't valid in this context

If you tried to supply `run` as a PATTERN use `-- run`

USAGE:
    youki [FLAGS] [OPTIONS] <SUBCOMMAND>

For more information try --help
```
Hello, I am very interested in the container runtime, but I don’t have much relevant experience. I noticed that the run command is not implemented.

And I can try to do it if you agree.

**Comment by Furisto** [comment]
Sure
