### ISSUE TITLE
Sharing types with containrs

### ISSUE THREAD

**Issue by saschagrunert** [containers/youki#162]
Hey folks, I think I do not have to mention that this is an interesting project. Great work so far! :clap: 

 I'd like to point to our other side-project `containrs`, which targets to implement a higher level runtime like containerd and CRI-O: https://github.com/cri-o/containrs

Do you think it would make sense to share some types, for example integrating them into youki and then re-using later on in our project? I see some overlaps, for example:

- in the OCI runtime spec: https://github.com/cri-o/containrs/blob/master/src/oci/spec/runtime.rs
- capabilities: https://github.com/cri-o/containrs/blob/master/src/capability.rs'
- seccomp: https://github.com/cri-o/containrs/blob/master/src/seccomp.rs

**Comment by Furisto** [comment]
Hi @saschagrunert, I wasn't aware of containrs, thank you for bringing this to my attention! Seccomp could be a good candidate I think, as we currently do not have an implementation for this yet. In the medium term I would like to pull more stuff from youki out into separate crates, like we already did for [spec](https://github.com/containers/youki/tree/main/oci_spec) in order to make it easier to write container tools in Rust.

**Comment by saschagrunert** [comment]
> In the medium term I would like to pull more stuff from youki out into separate crates, like we already did for [spec](https://github.com/containers/youki/tree/main/oci_spec) in order to make it easier to write container tools in Rust.

I agree this was also the idea behind conainrs. Glad to hear that the overall goal is the same :+1:

**Comment by utam0k** [comment]
@saschagrunert Thank you for contacting us.
I think it would be good for youki to allow other projects to use the code that youki is implementing now. It's a good idea to start with spec, what do you think?
Actually, I tried something like that before and it didn't work.
https://github.com/opencontainers/runtime-spec/issues/1106

**Comment by saschagrunert** [comment]
Sounds good to me, especially since the runtime spec is already in a dedicated crate within this repository. I think I can compare the implementations and double-check if we have some gaps between both.

**Comment by utam0k** [comment]
@saschagrunert Okay, first of all, let's make sure that `oci_spec` is shareable. However, I haven't come up with a good way to proceed as I've never done anything like that before. I have a feeling you know more about that point than I do. Do you have any specific ideas? I am working on OSS activities as a hobby, so my time is limited, but I am happy to help.

**Comment by saschagrunert** [comment]
Yes, so portability and conformance seems to be the most important parts. It looks like that some types are not optional right now, but the spec mentions them as optional (under certain conditions). Maybe we can use some external verification, for example with the [runtime-tools](https://github.com/opencontainers/runtime-tools).

**Comment by utam0k** [comment]
Currently, youki still uses runtime-tools. However, it seems that the development is not very active, so we are developing our own integration testing tool in youki.

Sorry, maybe this is my mistake.
> Yes, so portability and conformance seems to be the most important parts. It looks like that some types are not optional right now, but the spec mentions them as optional (under certain conditions).

BTW, who will take the initiative on this? Perhaps someone should be the driving force behind the project. If no one is interested, I can take the lead.

**Comment by saschagrunert** [comment]
Sounds good to me @utam0k! :)

Another note worth mentioning regarding the spec. It looks like that crun's libocispec is providing Rust bindings, too: https://github.com/containers/libocispec/tree/c9b8b9524814550a489aa6d38b2dec95633ffa15

**Comment by utam0k** [comment]
I'm a little busy, so I may be late, but I'll take care of it.
> Sounds good to me @utam0k! :)

I've thought about using it too. However, I thought it would be better to use pure Rust take advantage of Rust's advantages.
> Another note worth mentioning regarding the spec. It looks like that crun's libocispec is providing Rust bindings, too: https://github.com/containers/libocispec/tree/c9b8b9524814550a489aa6d38b2dec95633ffa15

For example, If I merge youki's oci_spec into cri-o/containers, I'm not sure what I should do about the license. Do you have any recommendations?

**Comment by saschagrunert** [comment]
> For example, If I merge youki's oci_spec into cri-o/containers, I'm not sure what I should do about the license. Do you have any recommendations?

I think it would be better to keep the OCI spec in an external crate like it is now. What do you think about that?

**Comment by utam0k** [comment]
@saschagrunert I think an external crate is a good idea, but I also think it is a good idea to make it selectable using features.
Do you have a design philosophy for the direction you want to take with the containers repository?
https://doc.rust-lang.org/cargo/reference/features.html

**Comment by saschagrunert** [comment]
I'm fine having features, for example we could also aim for building with no std to increase the portability.

How would we start? Do we wanna keep the oci_spec crate within this repository or do you prefer a new one? If yes, do we want to make this repository a workspace?

**Comment by utam0k** [comment]
@saschagrunert 
The name seems complicated to provide as a crate in this repository. So, how about creating a new repository in cri-o or modifying the current containers repository?
However, either way, I want someone from youki to have permission to access it.

**Comment by saschagrunert** [comment]
@utam0k would it also fit in the `containers` organization?

Something like: [containers/oci-spec-rs](https://github.com/containers/oci-spec-rs) ?

**Comment by utam0k** [comment]
I think it is good to develop it under the containers organization, but I'm not authorized to create repositories in their organization.

**Comment by saschagrunert** [comment]
I’ll try to get the repo in the next week. Let’s close this for now and focus on the OCI spec.
