### ISSUE TITLE
youki does not pass cargo test under certain circumstances

### ISSUE THREAD

**Issue by unknowndevQwQ** [containers/youki#1650]
At the time I ran into this problem, the git commit was fe58002c3.
Run cargo test --frozen --release and after waiting a while you will see the following:
```
test syscall::linux::tests::test_close_range_userspace ... ok
test seccomp::tests::test_basic ... ok
test syscall::linux::tests::test_close_range_native ... ok
test seccomp::tests::test_seccomp_notify ... ok
test syscall::linux::tests::test_get_open_fds ... ok
error: test failed, to rerun pass `-p libcontainer --lib`
```

**Comment by YJDoc2** [comment]
I have seen this once or twice before, but the issue with this is  when retried, even immediately, the tests pass, so it is either some race condition that occurs within tests or some cargo test assumptions which our tests somehow break.

One way I can think to proceed here is to make a script looping ~1000 times, running tests, seeing how many times they fail. Then annotating each test  to run serially  (or cargo might have a flag to do this) and see how many times we get failure there.

That way we can potentially rule out if it is some race condition in our tests or what.

A note is that running tests ~1000 times will take considerable time + resources , so whoever is doing , be careful!

**Comment by unknowndevQwQ** [comment]
> 

Wait, how should I test only one item and not all of them?
Before trying 1000 tests that will fail, I need to avoid testing tests that will definitely succeed at the same time, because that is too time consuming.

**Comment by Overflow0xFFFF** [comment]
I've been seeing a similar issue for a little bit now. With instructions from [this article](https://fdeantoni.medium.com/running-tests-sequentially-in-rust-eed7566f63f0), I was able to run tests sequentially with `cargo test -- --test-threads 1`:

```
test seccomp::tests::test_basic ... ok
test seccomp::tests::test_moby ... ok
test seccomp::tests::test_seccomp_notify ... ok
test signal::tests::test_conversion_from_string ... ok
test signal::tests::test_conversion_from_string_should_be_failed ... ok
test syscall::linux::tests::test_close_range_native ... ok
test syscall::linux::tests::test_close_range_userspace ... ok
test syscall::linux::tests::test_get_open_fds ... ok
test tty::tests::test_setup_console ... error: test failed, to rerun pass `-p libcontainer --lib`
```

I'm running rustc 1.67.0 (fc594f156 2023-01-24) on Fedora 36.

**Comment by Overflow0xFFFF** [comment]
No idea if this is correct at all, but I found my issue was stemming from the `libcontainer::tty::connect_stdio` function. I'm out of my element here, which is why I'm posting a diff in an issue versus creating a pull request. Regardless, this change seemed to work for me:

```diff
diff --git a/crates/libcontainer/src/tty.rs b/crates/libcontainer/src/tty.rs
index 37ee944f..3c4d4db6 100644
--- a/crates/libcontainer/src/tty.rs
+++ b/crates/libcontainer/src/tty.rs
@@ -11,6 +11,7 @@ use anyhow::{bail, Result};
 use nix::errno::Errno;
 use nix::sys::socket::{self, UnixAddr};
 use nix::unistd::close;
+use nix::unistd::dup;
 use nix::unistd::dup2;

 const STDIN: i32 = 0;
@@ -72,11 +73,14 @@ pub fn setup_console(console_fd: &RawFd) -> Result<()> {
 }

 fn connect_stdio(stdin: &RawFd, stdout: &RawFd, stderr: &RawFd) -> Result<()> {
-    dup2(stdin.as_raw_fd(), STDIN)?;
-    dup2(stdout.as_raw_fd(), STDOUT)?;
+    let sys_stdin = dup(STDIN)?;
+    let sys_stdout = dup(STDOUT)?;
+    let sys_stderr = dup(STDERR)?;
+    dup2(stdin.as_raw_fd(), sys_stdin)?;
+    dup2(stdout.as_raw_fd(), sys_stdout)?;
     // FIXME: Rarely does it fail.
     // error message: `Error: Resource temporarily unavailable (os error 11)`
-    dup2(stderr.as_raw_fd(), STDERR)?;
+    dup2(stderr.as_raw_fd(), sys_stderr)?;
     Ok(())
 }
```

The error seems to have stemmed from the original call to duplicate the stdout file descriptor:
```
dup2(stdout.as_raw_fd(), STDOUT)?;
```

My system wasn't happy with just passing file descriptor ints directly, so I duplicated the original file descriptors with `dup()` before copying them to the pseudoterminal with `dup2()`.

**Comment by YJDoc2** [comment]
@Overflow0xFFFF Thanks a lot for posting this!
This helps a lot than  my suggested approach :sweat_smile: 
I'll try to take a deeper look in this.

**Comment by yihuaf** [comment]
There has been a lot of code changed. I will close this issue for now since this doesn't seem to be actionable anymore.
