### ISSUE TITLE
Add cargo fmt command to make lint 

### ISSUE THREAD

**Issue by lengrongfu** [containers/youki#1717]
Current make lint just run `cargo clippy ` command , me hope add `cargo fmt` command to  `make lint` command for Makefile file.

**Comment by utam0k** [comment]
@lengrongfu I have the same idea. Let's do it!

**Comment by utam0k** [comment]
@lengrongfu Should I assign you?

**Comment by YJDoc2** [comment]
Hey  , I missed that when originally making the makefile :sweat_smile: Thanks for opening this and working on it :heart:
