### ISSUE TITLE
Plan for a new release?

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#1720]
@utam0k Do you think we have enough to cut a new release since the last release? I think the following PRs forms a good base for a new release and we can plan to add more features into the scope. Do we already have a process in place for how to plan and create a new release?

PR:
- #1484
- #1656 
- #1610 

On a broader discussion, do you think it is worth for us to create a release cadence? For example, we release a minor version every 3 month. We can use milestone to track.

**Comment by YJDoc2** [comment]
Hey, I think it is a good idea to release now, but I don't think we are at a place to  do a periodic release yet.
Also, we might want to update the vergen from 7.0->8.0 for this as well (?) #1725
