### ISSUE TITLE
Docker export in the tutorial

### ISSUE THREAD

**Issue by fantas1a** [containers/youki#1723]
Hi,

I encounter error when run the following command from the tutorial:
docker export $(docker create busybox) | tar -C rootfs -xvf -

It prompts that 'permission denied'. The details are given below. Can anyone give me some suggestions?

> $ sudo docker export $(docker create busybox) | tar -C rootfs -xvf -
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied
"docker export" requires exactly 1 argument.
See 'docker export --help'.
Usage:  docker export [OPTIONS] CONTAINER
Export a container's filesystem as a tar archive
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

> $ docker create busybox | tar -C rootfs -xvf -
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

> $ sudo docker create busybox | tar -C rootfs -xvf -
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
4b35f584bb4f: Pulling fs layer
4b35f584bb4f: Download complete
4b35f584bb4f: Pull complete
Digest: sha256:b5d6fe0712636ceb7430189de28819e195e8966372edfc2d9409d79402a0dc16
Status: Downloaded newer image for busybox:latest
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

> $ docker export busybox
cowardly refusing to save to a terminal. Use the -o flag or redirect

> $ docker export busybox rootfs
"docker export" requires exactly 1 argument.
See 'docker export --help'.
Usage:  docker export [OPTIONS] CONTAINER
Export a container's filesystem as a tar archive

> $ docker export --help
Usage:  docker export [OPTIONS] CONTAINER
Export a container's filesystem as a tar archive
Options:
  -o, --output string   Write to a file, instead of STDOUT

> $ docker export busybox
cowardly refusing to save to a terminal. Use the -o flag or redirect

> $ docker export -o busybox
"docker export" requires exactly 1 argument.
See 'docker export --help'.
Usage:  docker export [OPTIONS] CONTAINER
Export a container's filesystem as a tar archive

Thank you very much!

**Comment by utam0k** [comment]
@fantas1a Please run these commands as a root user like that:
```console
sudo docker export $(sudo docker create busybox) | tar -C rootfs -xvf -
```
