### ISSUE TITLE
Migrate OCI spec into dedicated repository

### ISSUE THREAD

**Issue by saschagrunert** [containers/youki#179]
We have a new repository available for the OCI spec: https://github.com/containers/oci-spec-rs

The main goal would be now to move over the code, setup the CI and make this repository dependent on it.

**Comment by utam0k** [comment]
@saschagrunert 
I apologize for the delay in replying. I am sick from the vaccine. When I'm feeling better, I'll try to migrate the current oci_spec code directly to oci-spec-rs. What do you think?

**Comment by saschagrunert** [comment]
> @saschagrunert
> I apologize for the delay in replying. I am sick from the vaccine. When I'm feeling better, I'll try to migrate the current oci_spec code directly to oci-spec-rs. What do you think?

Sounds good and no rush, nothing is pressuring. 😊 Feel better soon!

**Comment by nimrodshn** [comment]
@utam0k Feel better :pray:

**Comment by utam0k** [comment]
@saschagrunert I would like someone from the youki team to have write access to the oci-spec-rs repository, is that possible?

**Comment by saschagrunert** [comment]
> @saschagrunert I would like someone from the youki team to have write access to the oci-spec-rs repository, is that possible?

Yes, you should've got an invitation for the repository now.

**Comment by utam0k** [comment]
I missed it. Thank you!

**Comment by utam0k** [comment]
Thasnk! @saschagrunert
