### ISSUE TITLE
Youki exec a does not exist process will stop running container

### ISSUE THREAD

**Issue by lengrongfu** [containers/youki#1810]
# Steps to reproduce:

## Step 1
use `youki run -d {container_id}` command to start a container in background mode and keep the container running continuously.
and the container status will become `Running` after execution.

## Step 2
Use `youki exec -it {container_id} /bin/bash` to enter the container. If `/bin/bash` does not exist in the container, it will fail to enter the container, and the container status will become `Stopped` after execution.

I use runc to test, there is no such problem.

The following is the error exec log:
```
[DEBUG crates/libcontainer/src/capabilities.rs:135] 2023-04-13T14:32:53.549633813+08:00 dropping bounding capabilities to Some({AuditWrite, Kill, NetBindService})
[DEBUG crates/libcontainer/src/process/fork.rs:40] 2023-04-13T14:32:53.550891240+08:00 failed to run child process in clone: executable '/bin/bash' for container process does not exist
[INFO crates/libcgroups/src/common.rs:208] 2023-04-13T14:32:53.552311362+08:00 cgroup manager V2 will be used
[DEBUG crates/libcgroups/src/v2/manager.rs:132] 2023-04-13T14:32:53.552426219+08:00 remove cgroup "/sys/fs/cgroup/test"
exec failed : failed to create container
```

**Comment by yihuaf** [comment]
The fix is simple. I am surprised that this case is not covered with the integration test already. We should find a way to test this behavior.
