### ISSUE TITLE
Clean up and unify the use of tempdir and tempfile

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#1883]
Currently, we are rolling our own implementation of tempdir and duplicated the code in multiple places. In addition, I don't like the struct implements using `option<path>` and the `path()` has a `expect()` which can panic if called after remove. The proposed solution is to use `tempfile` crate. https://github.com/Stebalien/tempfile

- [x] libcontainer #1887 
- [x] youki #1887 
- [x] integration test #1891 
- [x] libcgroup #1888

**Comment by utam0k** [comment]
👍
