### ISSUE TITLE
Move cgroups into separate crate

### ISSUE THREAD

**Issue by Furisto** [containers/youki#189]
The cgroup implemenation could also be useful outside of youki. What do you think @utam0k

**Comment by utam0k** [comment]
I think it's good. First of all, I want to isolate it to crate in this repository.
cc: @saschagrunert

**Comment by tsturzl** [comment]
I see utility in perhaps implementing cgv1 and cgv2 as separate crate features which are both enabled by default, but you could then selectively exclude one or the other. This could be useful for projects with specific requirements, or making builds for platforms which might only support cgv1. It would be a nice to have if it's not too difficult.
