### ISSUE TITLE
cncf wasm workgroup

### ISSUE THREAD

**Issue by lengrongfu** [containers/youki#1901]
The current tag-runtine organization is preparing for wg-wasm, and those who are interested can pay attention.

https://docs.google.com/document/u/0/d/1bcMK0layzDCiKmpdIB7gShMv7nuqw3TkxUeLcxx91VU/mobilebasic

**Comment by utam0k** [comment]
@lengrongfu 
I have missed it, thanks. I left my comment ;)

**Comment by yihuaf** [comment]
Should we move this discussion to Discord and close this issue?

**Comment by utam0k** [comment]
Since we have nothing to do for now, I close it.
