### ISSUE TITLE
Does Youki support Linux kernel version 4. x? What is the minimum version of the kernel that can be supported?

### ISSUE THREAD

**Issue by wxmayifei** [containers/youki#1947]
I would like to use youki in prod environment~, however, the Linux kernel version I need to consider .

**Comment by utam0k** [comment]
@wxmayifei 👋 Hi, youki requires the kernel version >= 5.3, and we don't have a plan to support the old kernel 😭 
From README:
> Requires
Rust(See [here](https://www.rust-lang.org/tools/install)), edition 2021
linux kernel ≥ 5.3

**Comment by wxmayifei** [comment]
em. .......，
