### ISSUE TITLE
impl: exec sub command

### ISSUE THREAD

**Issue by minakawa-daiki** [containers/youki#20]
The exec command is not listed in the [runtime-spec](https://github.com/opencontainers/runtime-spec), but I consider it one of the required features. For example, when I run `docker exec -it [container id] bash`, I currently get the following error.

![Screenshot from 2021-05-22 19-39-11](https://user-images.githubusercontent.com/22878067/119223639-842af280-bb35-11eb-84c1-c9a3b96a9df2.png)

**Comment by minakawa-daiki** [comment]
@utamoku Can I have you assign me to solve this issue?

**Comment by utam0k** [comment]
@minakawa-daiki 
Thanks for your interest. Oh... That was definitely not implemented there.
I'd love to have it for you! I've assigned you to it.

**Comment by minakawa-daiki** [comment]
@utam0k May I remove the assignment because there may be someone else who wants to work on this issue?

**Comment by utam0k** [comment]
@minakawa-daiki 
I understand. Please challenge this again whenever you have time.

**Comment by Furisto** [comment]
@utam0k 
I can take a look at this

**Comment by utam0k** [comment]
@Furisto I'm looking forward to your PR.
