### ISSUE TITLE
Compiling youki gives an error message

### ISSUE THREAD

**Issue by Mossaka** [containers/youki#2019]
I cloned youki and ran `just youki-dev` and got this build error:

```bash
➜  youki git:(main) just youki-dev
./scripts/build.sh -o /home/mossaka/developer/youki -c youki
* FEATURES: 
* features: 
   Compiling libcontainer v0.0.5 (/home/mossaka/developer/youki/crates/libcontainer)
error[E0599]: no method named `get_notify_fd` found for struct `ScmpFilterContext` in the current scope
   --> crates/libcontainer/src/seccomp/mod.rs:263:17
    |
263 |             ctx.get_notify_fd()
    |                 ^^^^^^^^^^^^^ method not found in `ScmpFilterContext`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `libcontainer` (lib) due to previous error
error: Recipe `youki-dev` failed on line 14 with exit code 101
```

My env is x86_64 `Ubuntu 22.04`, kernel is `Linux 5.15.0` with `rustc 1.70.0`

**Comment by Mossaka** [comment]
Interestingly, I rebuilt youki in a ubuntu docker image and it succeeds. The following is the dockerfile, in addition to the necessary rust toolchains. 

```
FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu

RUN apt-get -y update
RUN apt-get install -y pkg-config libsystemd-dev libdbus-glib-1-dev libelf-dev libseccomp-dev
```

**Comment by YJDoc2** [comment]
Hey @Mossaka , can you check if the libseccomp version on your system is up-to-date and then try to do `just clean` and `just youki-dev` ? This kind of errors usually show up because the seccomp library version on system and libseccomp bindings youki uses mismatch

**Comment by Mossaka** [comment]
Yes, I have run 
```bash
sudo apt-get update -y
sudo apt-get install -y libseccomp-dev
```

and then have run
```
just clean
just youki-dev
```

but still got the same error.

**Comment by Mossaka** [comment]
To unblock myself, I have used `cross` to cross compile youki to the desired target that I want to use, which is `x86_64-unknown-linux-gnu`. Here is what I did:

### Install `cross`

```bash
cargo install cross --git https://github.com/cross-rs/cross
```

### Setup

Create a Dockerfile that roughly looks like this
```Dockerfile
ARG CROSS_BASE_IMAGE
FROM $CROSS_BASE_IMAGE

RUN apt-get -y update
RUN apt-get install -y pkg-config libsystemd-dev libdbus-glib-1-dev libelf-dev libseccomp-dev
```

And then create a `Cross.toml` manifest file to tell cross where the Dockerfile is

```toml
[build]
default-target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
dockerfile = "./Dockerfile"
```

### Build
Run `cross build --release --target x86_64-unknown-linux-gnu`

This will fetch and load a cross-built docker image, compile `youki` in this instance and then copy the artifacts back to `./target` directory. 

----

I shall clarify that, by performing the steps above, I was able to unblock myself to build youki successfully. Thus please feel free to close this issue.

**Comment by Mossaka** [comment]
Ah okay. Indeed I have an older version of `libseccomp-dev`. Upgraded and now can compile youki successfully! I am closing this issue now.
