### ISSUE TITLE
libcgroup build is broken for individual feature v1, v2 or systemd

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#2046]
Currently, we default the libcgroup feature to [v1, v2, systemd], so this went under our radar. However, if we compile libcontainer with individual features, the `libcgroups` fails to compile.

For example, this will fail.
```
cargo build --no-default-features --package libcontainer --features v2
```

**Comment by izissise** [comment]
I tried to update libcontainer/libcgroup in [aurae](https://github.com/aurae-runtime/aurae) but I got this error aswell

**Comment by yihuaf** [comment]
> I tried to update libcontainer/libcgroup in [aurae](https://github.com/aurae-runtime/aurae) but I got this error aswell

Yes, it is currently broken. We did not do a good job keeping this usecase working. I have a fix locally already, so I am hoping this can unblock you next week. I will follow up with works to make `libcontainer` tests running in CI so it is better maintained.
