### ISSUE TITLE
Move `ErrorKind`s into `error.rs` in their corresponding crates

### ISSUE THREAD

**Issue by simonsan** [containers/youki#2077]
Currently `ErrorKind`s are all over the place, defined where they are needed. This isn't great for visibility and also importing can get quite tedious, as it's not clear on first sight what error types a crate exposes. Which usually (AFAIK) is being done by looking into `error.rs`.

Another thing to think about is to use one opaque error type and implement something like an [ErrorMarker](https://github.com/rustic-rs/rustic/blob/main/crates/rustic_core/src/error.rs#L731) to be able to convert into that opaque error type:

```rust
// PublicError is public, but opaque and easy to keep compatible.
#[derive(Error, Debug)]
#[error(transparent)]
pub struct PublicError(#[from] ErrorRepr);

impl PublicError {
    // Accessors for anything we do want to expose publicly.
}

// Private and free to change across minor version of the crate.
#[derive(Error, Debug)]
enum ErrorRepr {
    ...
}
```

**Comment by yihuaf** [comment]
We don't use `ErrorKind` except `std::io::ErrorKind`.

**Comment by yihuaf** [comment]
I see. I was confused with the `ErrorKind` mention. Apologize.

Would you like to take a shot and draft a PR for this?

**Comment by yihuaf** [comment]
@simonsan Honestly, we don't have a good idea on this yet. We just recently migrated our error definitions from anyhow to structured errors using `thiserror`. We have not thought through all implications of proper error interface yet.

Can you point me to some readings or examples on opaque error type? Especially, if you can help us understand the trade offs between different approaches? Thanks.

**Comment by zahash** [comment]
@yihuaf  is this issue still open? if yes, can i be assigned?

**Comment by utam0k** [comment]
@yihuaf friendly remind ;) If you find time to address, feel free to let me know.
