### ISSUE TITLE
Pass the `root_read_only` integration test

### ISSUE THREAD

**Issue by utam0k** [containers/youki#209]
# Overview
Support read-only root directory.
https://github.com/opencontainers/runtime-spec/blob/master/config.md#process

# Goal
Pass the [root_read_only](https://github.com/opencontainers/runtime-tools/blob/master/validation/root_readonly_true/root_readonly_true.go) integration test in runtime-tools. 
If you comment in this part and the test passes, you are all set.
https://github.com/containers/youki/blob/a8427617836f98e904b504aa183b012d3c440b66/integration_test.sh#L42

# Reference
- [implementation of runc](https://github.com/opencontainers/runc/blob/4d26c4a0a14e55fb71a3f7be2d3cd9f228523fff/libcontainer/rootfs_linux.go#L794-L807)

**Comment by utam0k** [comment]
This is just the right task for those who haven't touched youki much.

**Comment by chenyukang** [comment]
Let me have a try.

**Comment by utam0k** [comment]
@chenyukang 
Of cource!
