### ISSUE TITLE
[Need Advice] Should we use double fork with child sub-reaper instead of clone_parent?

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#2112]
I have been trying to implement the clone fallback when clone3 returns ENOSYS. The clone interface is a pain to use correctly, because we have to take care of transferring memory to the child process. The libc `clone` does not provide a fork-like interface to clone, and we can't use clone kernel syscall directly bypassing libc.

We have two choices here. The first is to clone the `container_args`. It was clone-able, but we made it using references instead. This was how we made `clone` syscall working originally. We can clone the `container_args` and box the closure that capture this `container_args`. We do need to clone the struct 2 times, each time we clone the process. This will let us keep using `clone` but requires a more intrusive changes to the code base.

Alternatively, instead of working with the mess that is the libc clone, we can use `fork` which is a much more ergonomic interface. The problem with this approach is that we loose the ability to use `CLONE_PARENT` and potentially other clone flags in the future. `CLONE_PARENT` can be solved with using PR_SET_CHILD_SUBREAPER so the init process can be adopted by the main process when the intermediate process exits. This does deviate from how `runc` and `crun` implemented this part of the logic, but I believe the end result is the same in terms of correctness.

I think either approach would work and I don't have a particular preference. But I would like to get some consensus on the direction before I spend the time, since both approach requires a bit of work to implement.

@utam0k comments?

**Comment by utam0k** [comment]
There is two evaluation axis:
1. Ease of implementation
2. Impact on the binary size

I agree that this fallback should exist. On the other hand, this case is not the main case, so I don't think that complexity should be used with that much implementation cost. In other words, I don't mind the performance loss  in the fall back case.

**Comment by yihuaf** [comment]
I don't think binary size will be impacted because there is no new dependency being introduced with either approach. I also believe the performance hit with cloning memory or using `fork` is negligible at best. It is my understanding that there is no particular objections to either approach, then I will pick one and we can discuss in the PR.
