### ISSUE TITLE
Add support for rk8s

### ISSUE THREAD

**Issue by TimePrinciple** [containers/youki#2123]
We are trying to create a Rust written Kubernetes ecosystem, and [rk8s](https://github.com/open-rust-initiative/rk8s) is our replacement of `kubeadm` (this project is still under heavy development).
While we are trying to replace the default runtime of docker, and it indeed worked, the well-known hello world runs well:
![img_v2_fb41255d-29e4-435a-86eb-a9048a94be4g](https://github.com/containers/youki/assets/52569592/c2a120cd-02b6-4f2d-a09b-d2e233c1b521)
But error occured when appling calico, this it the output of `kubectl describe`:
![img_v2_b1481b16-27a7-4285-95ab-4cef640971dg](https://github.com/containers/youki/assets/52569592/38246d22-869e-4cd4-bd5b-ee42fd29ff54)
If I change the runtime back to runc, the kubernetes cluster works fine:
![jnTRuahXcz](https://github.com/containers/youki/assets/52569592/f92fe0dd-6b2a-4c81-968b-351c1ef40efc)

**Comment by YJDoc2** [comment]
Hey @TimePrinciple Can you provide a way to reproduce this, possibly locally? I tried pulling the calico image as the the pic you have attached, and start it locally but it does not run, maybe as it needs some extra configuration which I haven't done. If there is a way to reproduce this locally, I can try to debug and see what is the issue.
Does this setup store the logs generated by the runtime? If so they might be helpful for debugging as well.

**Comment by TimePrinciple** [comment]
To reproduce, `rk8s` need its `preparation` ready. This folder contains binary files (and compiled `youki` binary) downloaded from a specific URL, currently we are doing this by a pre-downloaded copy of them (due to the network limitations). I'll upload them in my Google Drive later this day, and share them here.
By the way, the working schema currently is deploying outside the cluster, which means you need at least 4 VMs to get the cluster working.

> Does this setup store the logs generated by the runtime?

`rk8s` is merely a deploy tool of kubernetes cluster, so as of `rk8s`, there is possibly nowhere to locate the problems happened in `youki`. If `youki` would produce execution log somewhere, then that would be helpful.

> If so they might be helpful for debugging as well.

To find output what happened when trying to start `youki`, may be `systemctl status docker` and `kubectl describe pod` command would be of help.

Thanks for your help.

**Comment by YJDoc2** [comment]
>By the way, the working schema currently is deploying outside the cluster, which means you need at least 4 VMs to get the cluster working.

Hey, I don't think I will be able to do this, but maybe someone else can try if they have resources.

>If youki would produce execution log somewhere, then that would be helpful.

youki does provide log through stderr or specified log destination, but as you said, rk8s is cluster deployment tool, so it would likely not have the logs.

As per from the pics, it seems that youki is failing when running the cni image, so the issue might be close to that. Is there any way I can run the cni image locally and test? I tried running it using docker, but even with runc it gives error of calico-conflast is not present.

**Comment by TimePrinciple** [comment]
I've currently uploaded all the binary files needed by the deployment process of `rk8s`, for anyone willing to reproduce this bug from scratch. Download the [binary files](https://drive.google.com/drive/folders/1x-0P2SYAEEO63ridZj28KxafZuY9W10f?usp=sharing) then put the contents in `/rk8s/preparation` folder, then `rk8s deploy` will do the rest job, right until the situation encountered in this issue.

> I tried running it using docker, but even with runc it gives error of calico-conflast is not present.

I'll look into this method later and try to reproduce this.

**Comment by YJDoc2** [comment]
Hey @TimePrinciple thanks for providing this. I'll try and see if I can get this up and working over the weekend, and in the meantime if you figure out running through docker, I'll try that as well. Thanks!

**Comment by TimePrinciple** [comment]
I'm trying to reduce the size of cluster to one node, then the cost would be narrowed down to 2 VMs of CentOS 9. I verified the deployment with `runc`, and then I change runtime to `youki`, the errors still  exist, here are the logs of `dockerd` and `systemd` I've found:
[logs.zip](https://github.com/containers/youki/files/12025500/logs.zip)

**Comment by utam0k** [comment]
@TimePrinciple May I ask you to use bpftrace(https://github.com/containers/youki/blob/main/hack/debug.bt) and find out what system call introduce this problem?

**Comment by utam0k** [comment]
Need more activity.
