### ISSUE TITLE
Prestart hook might be invoked too soon

### ISSUE THREAD

**Issue by penumbra23** [containers/youki#218]
Hi folks!

First thing, great project, love the idea and the usage of Rust for a container engine. :+1:

When running a container with `docker` using `youki` as a runtime, listing the network devices lists only the loopback device.
```
> docker run --rm -p 8080:80 --runtime youki alpine ip addr
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
```

Docker invokes the network plugins for creating the veth pairs and connecting them to the `docker0` bridge, adding iptable entries and default route. The container end of the veth pair gets "connected" to the container via a prestart hook (`libnetwork-setkey`) as the container state gets passed on `stdin`. 

The problem is that [youki calls the prestart hook before the fork call](https://github.com/containers/youki/blob/main/src/container/builder_impl.rs), so the container state doesn't have a PID which is needed to actually initialize the network interfaces on the container side (probably with `nsenter`).

Regards to the [OCI runtime spec for the deprecated prestart hook](https://github.com/opencontainers/runtime-spec/blob/master/config.md#prestart) it's only required to be called before the user-specific command, which can also happen after the `fork` call.

There could be a workaround for this particular `libnetwork` hook, but IMHO it should be correct to send the actual process PID to whatever other hook is being called, i,e. calling the prestart hook after the fork call.

Any opinion on this one?

**Comment by utam0k** [comment]
Thank you for the detailed report. I'll investigate the details later, but once I tried it at hand with the latest master, I couldn't reproduce it. If you don't mind, I'd like to know the results of `youki info`.
```
$ docker run --rm -p 8080:80 --runtime youki alpine ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
9: eth0@if10: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
$ ./youki info
Version           0.0.1
Kernel-Release    5.4.0-81-generic
Kernel-Version    #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021
Architecture      x86_64
Operating System  Ubuntu 20.04.2 LTS
Cores             12
Total Memory      15930
cgroup version    v1 and v2
cgroup mounts
  blkio           /sys/fs/cgroup/blkio
  cpu             /sys/fs/cgroup/cpu,cpuacct
  cpuacct         /sys/fs/cgroup/cpu,cpuacct
  cpuset          /sys/fs/cgroup/cpuset
  devices         /sys/fs/cgroup/devices
  freezer         /sys/fs/cgroup/freezer
  hugetlb         /sys/fs/cgroup/hugetlb
  memory          /sys/fs/cgroup/memory
  net_cls         /sys/fs/cgroup/net_cls,net_prio
  net_prio        /sys/fs/cgroup/net_cls,net_prio
  perf_event      /sys/fs/cgroup/perf_event
  pids            /sys/fs/cgroup/pids
  unified         /sys/fs/cgroup/unified

```

**Comment by penumbra23** [comment]
Wow, seems that the development goes rapid here 😄 I've pulled the latest code from the repo and now it works!

Keep the good work running!
