### ISSUE TITLE
Upgrade`oci-spec-rs`

### ISSUE THREAD

**Issue by utam0k** [containers/youki#225]
We are now using `oci-spec` by directly specifying the commit hash and repository. 
https://github.com/containers/youki/blob/a14ce13bcd7e97787dc3c9bf7f85d78cf728d9c5/Cargo.toml#L32
However, this has already been pushed to crates.io so that you can use it the same way as the others.
https://crates.io/crates/oci-spec

However, there are a few disruptive changes, so it's not straightforward, but none of them are that difficult.
https://github.com/containers/oci-spec-rs/compare/e0de21b89dc1e65f69a5f45a08bbe426787c7fa1...v0.3.0

I am looking forward to your challenge.

## Goal
Existing CI comes through using v0.3.0 of oci-spec.

**Comment by guni1192** [comment]
@utam0k  May I try this issue?

**Comment by utam0k** [comment]
@guni1192 Of course!

**Comment by guni1192** [comment]
@utam0k Sure I can!

**Comment by guni1192** [comment]
@utam0k 

`oci-spec-rs` and `youki` seem to use different rust toolchain.

`oci-spec-rs` v0.4.0 using unstable of rust features.

```
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /home/guni/.cargo/registry/src/github.com-1ecc6299db9ec823/oci-spec-0.4.0/src/lib.rs:2:10
  |
2 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
```

Therefore, `oci-spec-rs` must use nightly rust.
Now, `oci-spec-rs` use nightly rust on CI.
https://github.com/containers/oci-spec-rs/blob/a7b03bd2c7a20303550f9a0a5b4d17aa14ef7a77/.github/workflows/ci.yml#L78

However, youki uses stable rust on CI.
https://github.com/containers/youki/blob/03cb29ef4a8031b7f508f1758f33d918797f5701/.github/workflows/main.yml#L14

Do you have any solutions?

**Comment by guni1192** [comment]
@utam0k Oh, sorry. My rustc is an old version(1.52.0)
After `rustup update`,  I did `cargo build` .
That error didn't happen!
Thanks!

**Comment by utam0k** [comment]
@guni1192 np :+1:

**Comment by guni1192** [comment]
`FreezerState` has been removed from oci-spec-rs
https://github.com/containers/oci-spec-rs/pull/20

I'm thinking of porting it to `cgroups` crate if I implement it, is that ok?

**Comment by utam0k** [comment]
@guni1192 I owe you an apology. There may be another new version released. There is a possibility that this version will have a major change that will make the builder pattern the default. However, your efforts to upgrade to `0.4.0` will not be in vain.
The transition from `0.4.0` to `0.5.0` may be a bit tedious. Would you like to try it? If it looks boring, you can support up to `0.4.0` for once.
https://github.com/containers/oci-spec-rs/pull/61#issue-726620922

**Comment by guni1192** [comment]
@utam0k I'm in the process of working on this issue, but some of the fixes are taking a while.
I'm currently taking some time to fix a destructive change that caused `FreezerState` to disappear from `LinuxResource` in `oci-spec-rs`.

The transition to `0.5.0` is also quite interesting.
I'll start working on it as soon as I'm done migrating to `0.4.0`, if that's okay.

**Comment by utam0k** [comment]
Of course! Thank you very much. I'm looking forward to your PR :)

**Comment by guni1192** [comment]
@utam0k Hi, I would like to discuss a policy to fix a disruptive change in the oci-spec-rs update.

In oci-spec-rs, it was changed so that `caps::Capability` is no longer used for the type representation of `Capability`.
There are two possible implementation plans for youki.

- One is to create a layer to convert `caps::Capability` from `oci_spec::LinuxCapability`.
- The other is to change the implementation on youki side to apply the `Capabilities` in a `caps` independent way. This may be a bit more expensive to implement.

If you have any other good ideas, please let me know.

**Comment by utam0k** [comment]
@guni1192 Because I don't see any problem with dependence on the `caps` crate,  I prefer to create a layer that converts to `caps::Capability`. I think it is fine to use the `From` trait.
The only reason we removed the dependency on caps in `containres/oci-spec-rs` is to make the `oci-spec` crate a more generic crate, so don't worry about it.

**Comment by guni1192** [comment]
@utam0k OK. I understand.
I'll use the `From` trait.

**Comment by guni1192** [comment]
It should not have been possible to define a trait for a structure or enum defined in an external crate.
It is not possible to implement the `From` trait in youki source code for `caps::Capabilitiy` and `oci_spec::runtime::Capability`.
Therefore, I have implemented a temporary helper function in `src/capabilities.rs`.
If I have a better idea, I'll switch to it.

**Comment by utam0k** [comment]
Oops... You can use a helper function, or you can define a trait as shown in utils and have it implemented and extended.
https://github.com/containers/youki/blob/3cffe18944b3a0607c0a88a4322fee870f4b53fe/src/utils.rs#L16-L20

**Comment by guni1192** [comment]
It's a good idea. I try it.
Thanks.
