### ISSUE TITLE
Make `cgroupv2_devices` stable

### ISSUE THREAD

**Issue by utam0k** [containers/youki#2305]
https://github.com/containerd/runwasi/pull/249#discussion_r1303724489

**Comment by utam0k** [comment]
I gave it a try reproducing it, but I couldn't get errors 🤔 
```console
$ ./scripts/build.sh -o . -r -f libcontainer/cgroupsv2_devices
```

**Comment by YJDoc2** [comment]
I also tried building libcontainer with the cgroupsv2_devices , but couldn't reproduce error

**Comment by utam0k** [comment]
hmm... 🤔

**Comment by utam0k** [comment]
Please feel free to reopen if you find out how to reproduce this error.
