### ISSUE TITLE
Update nix to 0.27.*

### ISSUE THREAD

**Issue by YJDoc2** [containers/youki#2317]
ref : https://github.com/containers/youki/pull/2312
Nix has released a breaking version, and we need to do some corresponding code changes and verify that nothing is breaking.

**Comment by anti-entropy123** [comment]
Hi, I'm also working on resolving this issue. #2369. 
Feel free to offer suggestions.

**Comment by YJDoc2** [comment]
@anti-entropy123 please comment on the issue before you make the PRs especially if it is assigned to someone else already ... :slightly_smiling_face: 
@lengrongfu are you also working on this? Is it fine if I re-assign this?

**Comment by lengrongfu** [comment]
Of course, please redistribute it @YJDoc2 .thank you for your contribution @anti-entropy123 .

**Comment by YJDoc2** [comment]
this is closed via #2369 
Thanks @anti-entropy123 !
