### ISSUE TITLE
Refactor error handling and pass error to the parent process and/or caller of libcontainer

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#2389]
If the init process errors, we currently close the channel and exit. The only context around the error are in the logs/traces. This is not good UX for libcontainer interface. A better design is to return error through the channel back to the parent process so the parent process can log it and/or return to the caller.

**Comment by utam0k** [comment]
👍

**Comment by utam0k** [comment]
This is one of the most important features for us. It may seem surprising, but it will probably be a unique feature not found in any runtime.

**Comment by peter-jerry-ye** [comment]
May I ask if there's any workaround for now to get the error message?

**Comment by utam0k** [comment]
@peter-jerry-ye You can get the error message with bpftrace.
https://containers.github.io/youki/developer/debugging.html

**Comment by YJDoc2** [comment]
I think in my PRs for dbus and rootless related changes, I have covered most of the cases where we can catch and return errors from init process. I'll take another look to see if there are any remaining places and close this issue if not.

**Comment by YJDoc2** [comment]
I think this has been mostly addressed in the changes made since this issue. Closing this for now, can create a new issue with more specific aim if any other problem occurs.
