### ISSUE TITLE
feature request? allow customize the default cgroup root path

### ISSUE THREAD

**Issue by fengxsong** [containers/youki#2392]
As mentioned in the title, there are some usage scenarios that require this capability. we want to build an agent that depends on the crate `libcgroups`, and we're trying to run it in container as a daemonset workload, so it must mount the host's cgroup root path `/sys/fs/cgroup` as something like `/host/sys/fs/cgroup` in the container filesystem.

I'm not sure how to implement this in the current code base. consider this as a feature request or proposal.

If this proposal is accepted, I'll submit a PR on it.

**Comment by utam0k** [comment]
@fengxsong Thanks for your proposal.

It sounds good to me. But don't change the default path for cgroup. It means if the user doesn't pass the path of cgroup, we have to use `/sys/fs/cgroup`

Here is the default path for cgroup.
https://github.com/containers/youki/blob/6a9c78bb73305f19b9b97886eba38f571aec46ef/crates/libcgroups/src/common.rs#L26

**Comment by fengxsong** [comment]
@utam0k  is it ok to redefine the `DEFAULT_CGROUP_PATH`?

```rust
lazy_static! {
    pub static ref DEFAULT_CGROUP_ROOT: String =
        std::env::var("DEFAULT_CGROUP_ROOT").unwrap_or("/sys/fs/cgroup".to_string());
}
```

since type of `DEFAULT_CGROUP_ROOT` has changed from `&str` to `String`, then some refenced code will need to be changed.

**Comment by utam0k** [comment]
@fengxsong No, please pass it from libcontainer's builder pattern.

**Comment by YJDoc2** [comment]
@fengxsong can I ask you to make a PR updating docs and the migration guide regarding the changes done in https://github.com/containers/youki/pull/2411 , as it is part of public API of libcgroups ?

**Comment by fengxsong** [comment]
> @fengxsong can I ask you to make a PR updating docs and the migration guide regarding the changes done in #2411 , as it is part of public API of libcgroups ?

sure, but would you mind pointing out which docs need to be updated?

**Comment by YJDoc2** [comment]
Closing as completed, docs are also done :+1:
