### ISSUE TITLE
When using the host mount namespace, we should not pivot_root

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#240]
Scary things will happen if we run pivot_root without entering into a mount namespace. According to `runc`, we want to use chroot instead.

**Comment by utam0k** [comment]
Wow... Can you give me some runc reference in that area?

**Comment by yihuaf** [comment]
> Wow... Can you give me some runc reference in that area?

https://github.com/opencontainers/runc/blob/4d26c4a0a14e55fb71a3f7be2d3cd9f228523fff/libcontainer/rootfs_linux.go#L127
