### ISSUE TITLE
Pass oom_score_adj related integration test

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#246]
The goal of this issue is to uncomment this line and pass the integration test.
https://github.com/containers/youki/blob/2d02d22caf2763dd249d943f95d90374618eb10f/integration_test.sh#L64

The oom_score_adj is implemented already.
```rust
    // if Out-of-memory score adjustment is set in specification.  set the score
    // value for the current process check
    // https://dev.to/rrampage/surviving-the-linux-oom-killer-2ki9 for some more
    // information
    if let Some(ref resource) = linux.resources {
        if let Some(oom_score_adj) = resource.oom_score_adj {
            let mut f = fs::File::create("/proc/self/oom_score_adj")?;
            f.write_all(oom_score_adj.to_string().as_bytes())?;
        }
    }
```

However, it is not play nice with `prctl dumpable`, so the operation is actually not having the effect. Likely we have to understand how dumpable and oom_score_adj are interacting.

Ref: https://github.com/opencontainers/runc/blob/ba7a87730dd05937cb1c7f33528b1d460e620434/libcontainer/nsenter/nsexec.c#L651

**Comment by utam0k** [comment]
The goal of this issue is to uncomment this line and pass the integration test.
https://github.com/containers/youki/blob/2d02d22caf2763dd249d943f95d90374618eb10f/integration_test.sh#L64

**Comment by Onyinye91-ctrl** [comment]
@utam0k I will like to work on this issue

**Comment by utam0k** [comment]
@Onyinye91-ctrl sure!
