### ISSUE TITLE
Set network namespace in the container

### ISSUE THREAD

**Issue by jprendes** [containers/youki#2473]
From all the namespaces specified in the container spec, `youki` only sets the `user` and `pid` namespaces.
Other namespace, like the `nerwork` namespace, are ignored.

See https://github.com/containerd/runwasi/pull/364 and [this slack thread](https://cloud-native.slack.com/archives/C04LTPB6Z0V/p1698331231475599) for context.

**Comment by utam0k** [comment]
Thanks for creating the issue. Why did they think that? I think youki apply the rest of the namespace here:
https://github.com/containers/youki/blob/a6735b1c7e055d68f263624de767e952279fb5bc/crates/libcontainer/src/process/container_init_process.rs#L299

**Comment by jprendes** [comment]
You are 100% correct.
Youki is setting the network namespace, but for some reason it's not taking effect.
It might be related to what point in the container lifecycle the call is done, maybe the runwasi shim needs to create the container earlier.
I need to dig dipper into this.

**Comment by utam0k** [comment]
Pods share a network namespace among the containers, right? If it is right, perhaps runwasi is responsible for creating a network namespace for a pod. But I'm not sure...

**Comment by yihuaf** [comment]
> Pods share a network namespace among the containers, right? If it is right, perhaps runwasi is responsible for creating a network namespace for a pod. But I'm not sure...

This is how containerd-shim works. The network namespace is created upfront and the `OCI` runtime (runc in this case) will join the network namespace. `youki` implements all namespaces, both create and join existing. I did not dig into the containerd/runwasi codebase, but the idea would be for the containerd level to create the network namespace upfront, and pass the path of the network ns to `youki` as part of the runtime spec. `youki` should then join the network namespace correctly. Let me know if there is any issue.

**Comment by yihuaf** [comment]
Close this issue since `youki` does correctly setup the network namespace.
