### ISSUE TITLE
Support youki on linux arm64 platform

### ISSUE THREAD

**Issue by cuisongliu** [containers/youki#2485]

**Comment by utam0k** [comment]
@cuisongliu What do we need to support it?

**Comment by cuisongliu** [comment]
When we release youki, can we package amd64 and arm64 at the same time?

**Comment by cuisongliu** [comment]
https://github.com/containers/youki/releases/download/v0.3.0/youki_0_3_0_linux.tar.gz  It seems that there are only amd64 files here. Don't you support arm64 files?

**Comment by utam0k** [comment]
> When we release youki, can we package amd64 and arm64 at the same time?

Sure,  we can. Could you contribute?

**Comment by cuisongliu** [comment]
Yes, of course.

**Comment by utam0k** [comment]
@cuisongliu Thanks. I'm looking forward to seeing your PR ;)

**Comment by jhult** [comment]
@cuisongliu and @utam0k,

A new release hasn't come out since the PR was merged, but I think this can be closed now.
