### ISSUE TITLE
How to configure containerd to use youki instand of runc? Please provide the configuration guide.

### ISSUE THREAD

**Issue by hlb-source** [containers/youki#2501]

**Comment by cuisongliu** [comment]
https://github.com/containerd/containerd/blob/main/docs/cri/config.md#runtime-classes

**Comment by utam0k** [comment]
@hlb-source @cuisongliu 
Sorry, but we don't have the documentation for it. Could you contribute?
It will probably help you.
https://github.com/containers/youki/blob/28269200a5b0daf30f3d68c3f675db33bbfcf95a/tests/k8s/Dockerfile#L25-L32

**Comment by jprendes** [comment]
If you are using `containerd` through `docker` you can follow this guide:
https://docs.docker.com/engine/alternative-runtimes/#youki

**Comment by anti-entropy123** [comment]
@hlb-source  I've found that **ctr** supports a straightforward method for using youki instead of runc.

```bash
sudo ctr run -t --runc-binary /path/to/youki docker.io/library/ubuntu:latest youki-hello
```
You can also verify that it indeed uses youki by executing the command in another shell:
```bash
sudo ps auxf | grep -i youki
...
root     3041060  0.0  0.1 2217060 26880 pts/5   Sl+  11:03   0:00  |   |   |           \_ ctr run -t --runc-binary /path/to/youki docker.io/library/ubuntu:latest youki-hello
root     3041080  0.0  0.0 1236380 10536 ?       Sl   11:03   0:00 /usr/bin/containerd-shim-runc-v2 -namespace default -id youki-hello -address /run/containerd/containerd.sock
```
