### ISSUE TITLE
libcgroups v2 manager stats doesn't set cpu throttling field

### ISSUE THREAD

**Issue by Sherlock-Holo** [containers/youki#2513]
https://github.com/containers/youki/blob/77d31666bbf59a741c3bac5ad94ea4bf22480a8c/crates/libcgroups/src/v2/cpu.rs#L65

we can see the v2 manager `stats` doesn't set cpu throttling field, user can't get the `cpu.max` data when using v2 manager

**Comment by utam0k** [comment]
@Sherlock-Holo Thanks for your report. May I ask you to contribute?
