### ISSUE TITLE
Pass rootfs propagation test

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#256]
## Overview
Need to pass the linux_rootfs_propagation integration test

# Goal
Pass the [rootfs propagation](https://github.com/opencontainers/runtime-tools/blob/master/validation/linux_rootfs_propagation/linux_rootfs_propagation.go) integration test in runtime-tools. 
If you comment in this part and the test passes, you are all set.
https://github.com/containers/youki/blob/ef4b7932e80a91c67503325a76d322f0fc8f670b/integration_test.sh#L50

**Comment by tiqwab** [comment]
Can I take it if no one started yet?

**Comment by utam0k** [comment]
@tiqwab No one has started yet. I will assign you.
