### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by bestgopher** [containers/youki#2586]
```shell
-> root@10-252-51-190 ~/youki git:(main) 2? # just youki-release
/root/youki/scripts/build.sh -o /root/youki -r -c youki
* FEATURES: <default>
* TARGET: x86_64-unknown-linux-gnu
/root/youki/scripts/build.sh: line 60: FEATURES[@]: unbound variable
error: Recipe `youki-release` failed on line 19 with exit code 1
```

**Comment by bestgopher** [comment]
When I fixed this problem according to my understanding：
srcipts/build.sh#45L
```shell
FEATURES=("--features=default")
```
and new problems appeared:
```
error[E0599]: no method named `get_notify_fd` found for struct `ScmpFilterContext` in the current scope
   --> crates/libcontainer/src/seccomp/mod.rs:270:17
    |
270 |             ctx.get_notify_fd()
    |                 ^^^^^^^^^^^^^ method not found in `ScmpFilterContext`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `libcontainer` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: Recipe `youki-release` failed on line 19 with exit code 101
```

**Comment by bestgopher** [comment]
When I fixed the dependency in `crates/libcontainer/Cargo.toml`
```
libseccomp = {git="https://github.com/libseccomp-rs/libseccomp-rs",  optional = true, branch="main" }
```
, and install the `libseccomp(version >= 2.5.0)` library. The problem solved.

**Comment by YJDoc2** [comment]
Hey, Thanks a lot for reporting this!
The seccomp issue is most likely due to the seccomp library version installed on your system is older than what we require. Can you try upgrading it to latestand re-check? I'll take a look at the release build failure issue.

**Comment by YJDoc2** [comment]
Hey @bestgopher , I tried running `just youki-release` on the current main branch, and it worked without any issues. Can you give me more details about the build error you got initially ?

**Comment by bestgopher** [comment]
> Hey @bestgopher , I tried running `just youki-release` on the current main branch, and it worked without any issues. Can you give me more details about the build error you got initially ?

I cloned the repo and executed `just youki-release`, got the error
```
-> root@10-252-51-190 ~/youki git:(main) 2? # just youki-release
/root/youki/scripts/build.sh -o /root/youki -r -c youki
* FEATURES: <default>
* TARGET: x86_64-unknown-linux-gnu
/root/youki/scripts/build.sh: line 60: FEATURES[@]: unbound variable
error: Recipe `youki-release` failed on line 19 with exit code 1
```

**Comment by bestgopher** [comment]
@YJDoc2 
![image](https://github.com/containers/youki/assets/36840497/f364bf10-6bd8-4ea9-8566-b8b494b2f7e6)

**Comment by bestgopher** [comment]
The reason maybe the array is empty.https://github.com/containers/youki/blob/main/scripts/build.sh#L45

**Comment by jprendes** [comment]
What OS and shell are you using?
Is the bash command in you system actually running bash? Or some other shell?

**Comment by bestgopher** [comment]
@jprendes centos7.9 and zsh

**Comment by bestgopher** [comment]
@jprendes According to https://stackoverflow.com/questions/7577052/bash-empty-array-expansion-with-set-u, I will upgrade bash version and try again.

**Comment by bestgopher** [comment]
The first problem has been solved after I upgraded the bash version. But the second problem still exist.
![image](https://github.com/containers/youki/assets/36840497/53c9cfc7-5df7-4ee0-ac07-d40e9a1a6a41)

**Comment by YJDoc2** [comment]
> The first problem has been solved after I upgraded the bash version. But the second problem still exist.

Can you check which seccomp library version is installed on your system? This is usually due to the version incompatibility

**Comment by YJDoc2** [comment]
> I am sorry that I dont know how to get the version.

No worries : can you run `yum list installed | grep seccomp` and see its o/p ?

**Comment by bestgopher** [comment]
> > I am sorry that I dont know how to get the version.
> 
> No worries : can you run `yum list installed | grep seccomp` and see its o/p ?

I installed it from source, and the version is 2.5.3. When i upgraded the libseccomp(rust crate) version, it works fine.
edit the file: `crates/libcontainer/Cargo.toml`
```
libseccomp = {git="https://github.com/libseccomp-rs/libseccomp-rs",  optional = true, branch="main" }
```

**Comment by YJDoc2** [comment]
Hey @bestgopher , sorry I didn't get back to you on this. Changing dependency from crates.io to github should not have much difference as there don't seem to be any changes in their main branch from latest release (0.3.0). Can you try installing libseccomp from yum, and see if that works...

**Comment by bestgopher** [comment]
> Hey @bestgopher , sorry I didn't get back to you on this. Changing dependency from crates.io to github should not have much difference as there don't seem to be any changes in their main branch from latest release (0.3.0). Can you try installing libseccomp from yum, and see if that works...

Hi, thanks you for your reply. 
The difference between v0.3.0 and main branch shown as  follow:
https://github.com/libseccomp-rs/libseccomp-rs/blob/76a7530cb21ba2528ff644917a9e698280b1a735/libseccomp/src/lib.rs#L80

https://docs.rs/libseccomp/0.3.0/src/libseccomp/lib.rs.html#76

And the compile error maybe relate with the difference.
![image](https://github.com/containers/youki/assets/36840497/dfbeb3de-6921-4901-9da7-061d4ef0e909)

**Comment by utam0k** [comment]
We're going to switch our own seccomp from libseccomp. Please watch this issue 🙏
