### ISSUE TITLE
README.md of integration test is not up-to-date

### ISSUE THREAD

**Issue by Gekko0114** [containers/youki#2679]
Hi,
I am creating the environment running integration test.
However, this document is not up-to-date.
https://github.com/containers/youki/blob/main/tests/contest/contest/README.md
For example, crates/youki_integration-test directory doesn't exist.

Could you update the README of integration-test?

**Comment by utam0k** [comment]
@Gekko0114 Thanks for your report. I have fixed it.
https://github.com/containers/youki/pull/2680

If you want me to update other docs, please tell me. Of course, we are welcome to update the docs on your own.

**Comment by Gekko0114** [comment]
Thank you so much!
