### ISSUE TITLE
Convert unwraps to `?` and improve logging

### ISSUE THREAD

**Issue by YJDoc2** [containers/youki#2695]
Right now, after a certain point in the init process, the logs do not get forwarded to systemd/journalctl as we change the root mount. After that point we don't send the error back via the main sender to the main process either, so we don't get any error logs. Thus, if the init process fails due to any reason, we only get `Error waiting for init ready, pipe broken` as the log, which makes it hard to debug.

Also, there are several places where we have called `unwrap` on results, due to which the process panics, and as a result the errors are not propagated correctly. I think a better way here is to let the error propagate up by using `?` , so that users of our library (in our case youki) can handle them as they want, which is a better practice for libraries.

**Comment by YJDoc2** [comment]
@utam0k @jprendes May I ask you to take a look at above, and let me know if you have any suggestions, comments or concerns in this? I will work on this accordingly. Thanks!

**Comment by utam0k** [comment]
Good idea. Let's move on to the next step. How about establishing the procedure that produces this error message for starters?

**Comment by utam0k** [comment]
https://github.com/containers/youki/pull/2705#issuecomment-1961344115

**Comment by yihuaf** [comment]
Is there anything still left to do for this issue?

**Comment by utam0k** [comment]
From my view, nothing. @YJDoc2  WDYT?

**Comment by YJDoc2** [comment]
No, we can close this one, and be careful of unwraps in the code changes we do :+1:
