### ISSUE TITLE
Update nix to 0.28.0

### ISSUE THREAD

**Issue by YJDoc2** [containers/youki#2723]
ref : https://github.com/containers/youki/pull/2712

Nix update has some breaking changes , specifically in terms of deprecated fns , so need to update those to use non-deprecated things instead.

**Comment by omprakaash** [comment]
Hey can I take up this issue ?

**Comment by YJDoc2** [comment]
> Hey can I take up this issue ?

Yep, thanks! Assigned :+1:

**Comment by zahash** [comment]
i think a few types like `ContainerType::TenantContainer { exec_notify_fd: RawFd }` 
must be changed to `ContainerType::TenantContainer { exec_notify_fd: OwnedFd }`

because in a few places like `TenantContainerBuilder::build` we get a `OwnedFd` but soon convert it to a `RawFd`.

```rust
        let (read_end: OwnedFd, write_end: OwnedFd) =
            pipe2(OFlag::O_CLOEXEC).map_err(LibcontainerError::OtherSyscall)?;

        let mut builder_impl = ContainerBuilderImpl {
            container_type: ContainerType::TenantContainer {
                exec_notify_fd: write_end.as_raw_fd(),
            },
            ...
            
```
