### ISSUE TITLE
Make our roadmap public

### ISSUE THREAD

**Issue by utam0k** [containers/youki#2821]
https://github.com/orgs/containers/projects/15

**Comment by utam0k** [comment]
@lsm5 Hi, 👋 Do you have permission to make it public? Apparently, I don't have enough permission to do that.
https://github.com/orgs/containers/projects/15

**Comment by lsm5** [comment]
> @lsm5 Hi, 👋 Do you have permission to make it public? Apparently, I don't have enough permission to do that. https://github.com/orgs/containers/projects/15

@utam0k done. let me know if any issues.

**Comment by utam0k** [comment]
Thanks! It works fine.
