### ISSUE TITLE
Update nc from 0.8.23 to 0.9.1

### ISSUE THREAD

**Issue by YJDoc2** [containers/youki#2874]
In this major version update, there is an API breaking change in nc, which we have to fix manually. I believe the fixes are easy to do and validate, but still need to be done properly as they touch some of our imp code parts.

See https://github.com/containers/youki/pull/2873 for  breakage info via lint.

**Comment by aidanhs** [comment]
FWIW this bump makes musl static builds break for me with

```
  = note: /nix/store/a1l57qpyyr8rpxxk26lldv42fcjvps6h-x86_64-unknown-linux-musl-binutils-2.35.1/bin/x86_64-unknown-linux-musl-ld: /home/aidanhs/zircon/target/x86_64-unknown-linux-musl/release/deps/libnc-84a6815abfb93d73.rlib(nc-84a6815abfb93d73.nc.2c2307cd896e3a7-cgu.3.rcgu.o): in function `__restore_rt':
          nc.2c2307cd896e3a7-cgu.3:(.text+0x0): multiple definition of `__restore_rt'; /nix/store/hcd122h1i7ablkh2ygc2qjlkjvnzyf3i-rust-1.81.0-nightly-2024-07-19-9057c3ffe/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/libc.a(restore.lo):/build/musl-cross-make/build/local/x86_64-linux-musl/obj_musl/../src_musl/src/signal/x86_64/restore.s:6: first defined here
```

My best guess at a quick look is that the musl `__restore_rt` is defined like so https://github.com/bminor/musl/blob/dd1e63c3638d5f9afb857fccf6ce1415ca5f1b8b/src/signal/x86_64/restore.s#L5-L7

```
__restore_rt:
	mov $15, %rax
	syscall
```

`nc` used to use the same implementation, so I believe the linker could deduplicate the symbols. But this changed to a custom implementation:

https://github.com/XuShaohua/nc/commit/b67d499b1a26909c4c4657086011ee9d973b4ad8#diff-685ac5a9e7e590059d38c8c235bd2b94b36a9e15a7743baa045a7f4383100158L6-L8
