### ISSUE TITLE
[Bug]: Musl static linking support is broken

### ISSUE THREAD

**Issue by aidanhs** [containers/youki#2894]
### Bug Description

https://github.com/containers/youki/issues/2874#issuecomment-2307966181

Only solution I can see right now is to downgrade `nc`.

### Steps to Reproduce

```
$ cargo build -p youki --no-default-features --features 'v1 v2' --target x86_64-unknown-linux-musl
[...]
  = note: /usr/bin/ld: /home/aidanhs/youki/target/x86_64-unknown-linux-musl/debug/deps/libnc-9db00929dc01a4f6.rlib(nc-9db00929dc01a4f6.nc.4fffa74083c2fef3-cgu.3.rcgu.o): in function `__restore_rt':
          nc.4fffa74083c2fef3-cgu.3:(.text+0x0): multiple definition of `__restore_rt'; /home/aidanhs/.rustup/toolchains/1.80.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/libc.a(restore.lo):/build/musl-cross-make/build/local/x86_64-linux-musl/obj_musl/../src_musl/src/signal/x86_64/restore.s:6: first defined here
          collect2: error: ld returned 1 exit status
```

### Expectation

Shoould compile

### Additional Context

I raised https://github.com/XuShaohua/nc/issues/34

**Comment by YJDoc2** [comment]
I have updated nc to 0.9.3 in main, will  try to get youki 0.4.1 released.

**Comment by XuShaohua** [comment]
👌

**Comment by YJDoc2** [comment]
Hey @aidanhs , @XuShaohua can you check with youki's main branch and see if the nc related issues are resolved? I have opened a PR for new point release of youki, but wanted to confirm if the issues are fixed or not.

**Comment by XuShaohua** [comment]
`cargo build` got error:

```bash
error[E0599]: no method named `get_notify_fd` found for struct `ScmpFilterContext` in the current scope
   --> crates/libcontainer/src/seccomp/mod.rs:266:17
    |
266 |             ctx.get_notify_fd()
    |                 ^^^^^^^^^^^^^ method not found in `ScmpFilterContext`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `libcontainer` (lib) due to 1 previous error
```

While `cargo build -p youki --target x86_64-unknown-linux-musl` is ok.

So I believe the symbol name confliction issue is gone.

**Comment by YJDoc2** [comment]
Can you check the libseccomp version installed on your system? Youki requires 2.5+ version.

On my system I ran `cargo build` which ran fine.

**Comment by XuShaohua** [comment]
```bash
Package: libseccomp2
Source: libseccomp (2.5.5-1)
Version: 2.5.5-1+b1
```

**Comment by XuShaohua** [comment]
I've found the reason.

1. `pub fn get_notify_fd(&self) -> Result<ScmpFd>` is defined in libseccomp::notify module
2. That `notify` module is cfg with `#[cfg(any(libseccomp_v2_5, doc))]`
3. And `libseccomp_v2_5` feature is setup in build.rs:
```rust
    if pkg_config::Config::new()
        .atleast_version("2.5.0")
        .probe("libseccomp")
        .is_ok()
    {
        println!("cargo:rustc-cfg=libseccomp_v2_5");
    }
```
4. But I've installed `libseccomp-dev` after `cargo build` raise error
5. I've forgotten to run `cargo clean`!

And now `cargo build` is ok!

😅

**Comment by aidanhs** [comment]
Yep this particular issue seems fine now, thanks for the quick fix @XuShaohua !

**Comment by XuShaohua** [comment]
You are welcome!在 2024年8月31日，02:22，Aidan Hobson Sayers ***@***.***> 写道：﻿
Yep this particular issue seems fine now, thanks for the quick fix @XuShaohua !

**Comment by YJDoc2** [comment]
Apologies for the delay, 0.4.1 is released with updated nc, and should fix the issues
