### ISSUE TITLE
glibc-static listed for debian in README.md

### ISSUE THREAD

**Issue by morganllewellynjones** [containers/youki#2903]
### Bug Description

This may not be a bug at all, but the README lists glibc-static as a dependency on debian systems. I'm developing locally on debian, and as far as I can tell, there is no such package a glibc-static in the apt repositories.

### Steps to Reproduce

Using docker:

```bash
docker run -it debian:12 /bin/bash
apt-get update -y && apt-get upgrade -y && apt-get install glibc-static
```

### Expectation

Do we need to add a certificate for glibc-static? Is it even necessary? It seems strange to try to dynamically link glibc on a linux system, even if you could.

**Comment by YJDoc2** [comment]
Hey, thanks for reporting! This is probably outdated docs or mistakenly added dep. I'll take a look and update.
