### ISSUE TITLE
Bump oci-spec from 0.6.8 to 0.7.0 

### ISSUE THREAD

**Issue by utam0k** [containers/youki#2920]

**Comment by YJDoc2** [comment]
@kiokuless , any chance you'd be able to get to this by this weeked? There is another PR that has some dependencies on this, https://github.com/containers/youki/pull/2837 , so would like to get this done if possible. No problem if you're busy, but let me know. Thanks :)

**Comment by kiokuless** [comment]
@YJDoc2 @utam0k Thanks for the heads-up! I just submitted the PR. Sorry for the late submission of it...

**Comment by YJDoc2** [comment]
> Sorry for the late submission of it...

Oh, no worries, I was just checking. Thanks a lot of speedy update and PR on this! :purple_heart:

**Comment by YJDoc2** [comment]
closed via #2934 
Thanks @kiokuless !
