### ISSUE TITLE
[Tracking Issue] Upgrade `oci-spec-rs`

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#299]
There are a few major and breaking changes since `oci-spec-rs` repo is broken off. We should catch up as soon as possible to avoid bigger gap. Using this as tracking issue.

- [X] Upgrade to 0.4.0 #266 
- [x] Upgrade to 0.5.0 #303 
- [x] Upgrade to 0.5.1 #303 
- [ ] Upgrade to 0.5.2 #329

**Comment by utam0k** [comment]
@guni1192 Has development already started?

**Comment by yihuaf** [comment]
If @guni1192 hasn't started, I can help to finish this. This is probably a higher priority.

**Comment by guni1192** [comment]
@utam0k @yihuaf 
The cgroup crate has been updated to oci-spec-rs 0.5.1.
Work is in progress on youki.
There may be a lot of rewriting of tenant_builder.rs.
I'm trying to submit a Draft PR on Saturday.

**Comment by utam0k** [comment]
@guni1192  Is it possible to send out PR only for cgroups first? I believe separate PRs for `src` and `cgroups` would be simpler to review.

**Comment by guni1192** [comment]
@utam0k OK, I'll give it a try.
However, it may fail to resolve some dependencies.

**Comment by yihuaf** [comment]
Use #329 to track.
