### ISSUE TITLE
Pass linux_process_apparmor_profile integration test

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#300]
## Overview
Need to pass the linux_process_apparmor_profile integration test

# Goal
Pass the [apparmor](https://github.com/opencontainers/runtime-tools/blob/master/validation/linux_process_apparmor_profile/linux_process_apparmor_profile.go) integration test in runtime-tools. 
If you comment in this part and the test passes, you are all set.
https://github.com/containers/youki/blob/ef4b7932e80a91c67503325a76d322f0fc8f670b/integration_test.sh#L48

**Comment by utam0k** [comment]
@Furisto may have already started developing this.
https://github.com/containers/youki/issues/252#issuecomment-909166445

**Comment by yihuaf** [comment]
@Furisto I see a lot of things on your plate. Let me know if I can help with this one or any other.

**Comment by Furisto** [comment]
I have started working on this but encountered some difficulties. Runc also fails this test on my system with the same error as my solution. Considering that this I use the same distro as our CI I expect the problem to manifest also there. I will continue to investigate this. Should I not be able to make progress until next monday, I will open this up to anyone else who is interested.

**Comment by Furisto** [comment]
Ok, got it. The test uses an apparmor profile that does not exist. We need to create it ourselves and install it before the test is run.

**Comment by yihuaf** [comment]
Great find. May be manually verify it with installing the required apparmor profile and adds a comment to integration_test.sh? We will have our own integration framework done soon and will start porting the tests. I don't think it is worth it to put it into the CI workflow.

**Comment by yihuaf** [comment]
Fixed by #312

**Comment by utam0k** [comment]
@yihuaf I want to track it so that I don't forget to create the original integration test. How about using this issue to complete that?

**Comment by yihuaf** [comment]
@utam0k We certainly can. With that being said, I think we will have to port over all integration tests to our own framework, and this app armor test is only one of the 50ish tests. We also have a number of tests don't pass for runc and are commented out at the moment. May be we should create separate issues for the porting effort? I am sure we will not forget about this, since we have the list inside `integration_test.sh`.
