### ISSUE TITLE
Capitalization of error messages

### ISSUE THREAD

**Issue by Furisto** [containers/youki#313]
We have mixed capitalization in error messages in youki e.g.
```
Failed to run post stop hooks
no linux in spec
```
I so far have used lowercase with no period because that is what is described in the [api guidelines](https://github.com/rust-lang/api-guidelines/issues/79) and also what the compiler itself [uses](https://github.com/rust-lang/rust/issues/442). Personally I do not really care what we use as long as we do it consistently.  We do not need to change anything now, just something to keep in mind, when you touch code. Let me know what you want to do.

@utam0k @yihuaf @YJDoc2

**Comment by yihuaf** [comment]
I think we should follow the api guideline. I don't really have a preference either way, but I agree we should standardize it. The api guideline looks reasonable and something we can point to in the future.

**Comment by YJDoc2** [comment]
I don't have a preference, but agree that we should have some consistent formatting.

I'd suggest rather than fixing messages in a dedicated commit, and possibly causing conflicts, let us update message in whichever files we change, and uphold this formatting in new PRs, that way eventually most/all messages will confirm to this.

**Comment by utam0k** [comment]
You're right, it's better to unify. If we are going to unify, we want to follow the api guidelines. It would be great to have a tool to check them.
This is a bit off topic, but I'm also thinking a bit about introducing thiserror.

**Comment by Furisto** [comment]
Great! Then the decision is to follow the rust api guidelines and use lower case for error messages.
