### ISSUE TITLE
Fetch oci-spec-rs from crates.io.

### ISSUE THREAD

**Issue by guni1192** [containers/youki#329]
Fetch oci-spec-rs from git, not from crates.io.
We are using git hash to modify the version of oci-spec-rs.
This is because a version incorporating this PR (https://github.com/containers/oci-spec-rs/pull/69) has not yet been released.
We will update the minor version of oci-spec-rs as soon as it is released.

ref: #303

**Comment by yihuaf** [comment]
@utam0k I was thinking may be we should maintain git commit hash for this until `oci-spec-rs` is stable? It seems that we constantly are finding kinks to iron out between the spec repo and youki.

**Comment by utam0k** [comment]
I agree with you :+1:
