### ISSUE TITLE
Run tests used in various high-level container runtimes

### ISSUE THREAD

**Issue by utam0k** [containers/youki#331]
## Overview
The actual use of youki is high-level container runtime. So the ci should be included to make sure that it can be used with some of the major high-level container runtimes.

## Target
- Docker
- Podman
- containerd
- cri-o

**Comment by nasirhm** [comment]
Sure, I would like to work on it.

**Comment by nasirhm** [comment]
Thank You @utam0k , Are we planning to set up CI Pipelines to test Youki with Docker, Podman, Containerd and CRI-O ?

**Comment by utam0k** [comment]
> Are we planning to set up CI Pipelines to test Youki with Docker, Podman, Containerd and CRI-O ?

Yes, however,  if you have a better way, that is fine.

**Comment by utam0k** [comment]
Duplicate #584 #585

**Comment by gattytto** [comment]
> @Yuan-Zhuo I'm not familiar with containerd, however, this document may help you. You may be able to use it by changing `runtime` to the path of the youki binary. If you succeed in getting it to work, I'd like to add documentation on how to do it.
> 
> > I am trying to find a way to tell containerd to use the youki instead of runc. But I don’t know how to do. Is there some relevant documents?

I have been playing around to integrate other runtimes to cri-o for use with kubernetes in different scenarios, like single-node clusters, different architectures (like arm) and different host underlying filesystems (zfs/lvm/xfs), and then trying to find the more canonical way to implement them by using templates (lxc, snap, aptitude, yaml for kubernetes finally). 

I hink this solution has 2 parts:
part 1: figuring the way to implement the runtime in the different situations individually for all architectures and operating systems as possible: windows-containers-shim(is a thing!!), cri-o, containerd, docker.

part 2: make a cluster-wide solution to be implemented in orchestrators (aws/gce/kubernetes/openshift) as they all comply to the same standard. This part could be consisted of:
* 1: cluster-wide runtimeClass, maybe tags(selectors in kube-slang) to specify arch/os/distro(dinamically/statically built)
* 2: runtime-operator (set up a CRD and an operator) that keeps track and updates pods
  * calico is a good example, set up each node with a pod and mount a folder in it to inject the runtime bins from the pod and the configuration files (in node's /opt/cni folder and /etc/cni respectively) from the deployments yaml. This will make it way easier to detect node's specs from the yaml using $VARS.

**Comment by utam0k** [comment]
> Sorry for replying in this instead of opening a new one.(I think my question is very similar to this one. )
> 
> I am trying to find a way to tell containerd to use the youki instead of runc. But I don’t know how to do. Is there some relevant documents?

Thanks for your advice. Now, I'm trying this!
https://github.com/containers/youki/pull/514
