### ISSUE TITLE
Support for cgroup mount types

### ISSUE THREAD

**Issue by utam0k** [containers/youki#332]
We are looking for a challenger for this issue.

We will have to look at the runc code to determine what needs to be done.
https://github.com/containers/youki/blob/4224d5635dccc345ca6864fe661527a251b1a08b/src/rootfs.rs#L57-L59

**Comment by Furisto** [comment]
Looks like we need to add the Init process to the cgroup from Main, then notify Intermediate that we have done so, which will send it to Init. Init in the meanwhile is waiting to receive the notification that the cgroup has been applied, then it can proceed with setting up rootfs.

**Comment by utam0k** [comment]
> Looks like we need to add the Init process to the cgroup from Main, then notify Intermediate that we have done so, which will send it to Init. Init in the meanwhile is waiting to receive the notification that the cgroup has been applied, then it can proceed with setting up rootfs.

Did you read the runC code? I you don't mind, can you give me a link to the code that handles that area?

**Comment by Furisto** [comment]
Looks like they somewhat recently reworked the code in that area and I was looking at an outdated version but these commits give a good overview:
- https://github.com/opencontainers/runc/commit/df3fa115f97407713ec6ebe37a5ccf13b81dafd2
- https://github.com/opencontainers/runc/commit/5110bd2fc026c0a9849e35322d5b81a3f28c716d

**Comment by Furisto** [comment]
I can take this
