### ISSUE TITLE
Delete a container that has been created but is not running

### ISSUE THREAD

**Issue by zidoshare** [containers/youki#337]
Why is it not allowed to delete a container that has been created but is not running?

when I run 
```shell
$ sudo ./youki create -b tutorial tutorial_container
$ sudo ./youki delete tutorial_container            
[DEBUG src/commands/delete.rs:17] 2021-09-26T22:40:49.678849156+08:00 start deleting tutorial_container
[DEBUG src/container/container_delete.rs:36] 2021-09-26T22:40:49.679505848+08:00 container status: Created
Error: failed to delete container tutorial_container

Caused by:
    tutorial_container could not be deleted because it was Created
```

This is successful in runc：

```shell
$ sudo runc create -b tutorial tutorial_container
$ sudo runc create -b tutorial tutorial_container
```

**Comment by Furisto** [comment]
You can delete it if you specify --force. The runtime spec specifies that trying to delete any container that is not in state stopped [must create an error](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#delete). So if runc allows that, it is a violation of the spec.

**Comment by zidoshare** [comment]
I understand, I will close this issue
