### ISSUE TITLE
Create a flat design version of the icon 🙏

### ISSUE THREAD

**Issue by utam0k** [containers/youki#344]
I'm not very good at design, so I'm looking for someone who is good at it. Please refer to the README logo for an image.

**Comment by rapiz1** [comment]
I'm curious about what the [logo](https://github.com/containers/youki/raw/main/docs/youki.png) is after all? Is it a shield?

**Comment by redthing1** [comment]
it's a rusty container

**Comment by cr0ax** [comment]
![rustycontainerflat](https://user-images.githubusercontent.com/60494319/154420186-e98dfbb4-8c85-48b2-8624-0e94dfeefd3b.png)

?

**Comment by utam0k** [comment]
@cr0ax Can you even design! Wonderful 😍

**Comment by yihuaf** [comment]
This is really good!! Thanks @cr0ax

**Comment by ShadowJonathan** [comment]
@cr0ax that "eye" on the left side of the container initially made me thought this was kind of a deformed ferris...

I'd recommend making it a bit more jagged or less "eye"-like like the original pixelated logo, as that may help with mental ferris-pattern-matching :sweat_smile:

**Comment by chenyukang** [comment]
@cr0ax thanks for creating it. It think the color is good.
But seems there are too many elements in the picture, besides it's a three-dimensional container.
@utam0k , can we use a flat container? 😉

**Comment by scary4cat** [comment]
![rustycontainer_v2](https://user-images.githubusercontent.com/10859042/159714139-dd09f6bf-e023-45b0-84c7-0738834d1e8f.png)

![rustycontainer](https://user-images.githubusercontent.com/10859042/159714358-88c2298f-4fb1-4ec9-8fcb-8905e9b29359.svg)

srry meant to edit this a while ago but got distracted... also hi turns out i hav a github account
attaching the original svg so others can make changes to the design if they want. personally i wanted to keep it in perspective because imo hexagon is more interesting than square for icon silhouette...

**Comment by ShadowJonathan** [comment]
This looks fine, thanks a lot!

**Comment by utam0k** [comment]
@scary4cat Wow! Amazing. I love this ❤️  I'm curious to see your other ideas. You don't have to stick to the previous design, especially if it's a rusty container and a flat design. By the way, I don't have any sense of design at all, so I envy your ability.
If you don't have time I really like the current one too. Would you be willing to send me a PR under `docs/`? If this is too difficult, please go to me. I can do it myself but would like to be your contributor if possible.

**Comment by utam0k** [comment]
Special thanks @scary4cat

**Comment by kotx** [comment]
Not that it contributes to any productive discussion, and no offense to anyone, but I preferred the old logo. It really stood out with the level of detail and frankly resembles a container more than the flat version. Would love to see it back.

**Comment by utam0k** [comment]
@kotx Thanks for your advice. I didn't delete the previous log from the repo.
