### ISSUE TITLE
[Discussion] Share code between youki_integration_test and youki

### ISSUE THREAD

**Issue by yihuaf** [containers/youki#396]
It is inevitable that the youki_integration_test and youki will share some code. For example, the definition of container state is already duplicated, as well as tempdir from util. Should we find a way to share code between youki and youki_integration_test?

One proposal is to make most part of Youki into a library crate and Youki binary as another crate. Then we can make youki_integration_test another binary crate and share the youki library crate.

@utam0k @YJDoc2 @Furisto would love to hear your opinions on this.

**Comment by yihuaf** [comment]
This is almost exactly what I have in mind as well. A few minor things. How about we call `containers` crate `libcontainer` to reflect that it is a library crate? Should we separate integration tests and the test framework into first level crate as well?   
```
crates
  - ... (what you mentioned above)
  - test/integration_test (bin crate)
  - test/framework (library crate)
hack
docs
...

```

**Comment by Furisto** [comment]
I would like to do it. I have a free day tomorrow, so even if it turns out to be more complicated I should be finished tomorrow latest.

**Comment by yihuaf** [comment]
Go right ahead then :)

**Comment by utam0k** [comment]
Thanks for the great suggestion. Let's try it. `lib*` is a traditional name in the container runtime community, but I haven't seen it used elsewhere as a library much. Let's try to find a name that works best for us.
Please add me as a PR reviewer.
