### ISSUE TITLE
Switch to new Rust edition

### ISSUE THREAD

**Issue by Furisto** [containers/youki#404]
Now that a new rust edition has been [released](https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html) we should [switch](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html) to the new edition, provided we do not see an [increase](https://old.reddit.com/r/rust/comments/qdivb5/156_compile_time_is_through_the_roof/) in compile times.

**Comment by YJDoc2** [comment]
Hey, now that #405 is merged, can we close this issue?

**Comment by Furisto** [comment]
@YJDoc2 yes
