### ISSUE TITLE
First release blog

### ISSUE THREAD

**Issue by utam0k** [containers/youki#44]
Write an article for the first release of youki.

**Comment by utam0k** [comment]
@yihuaf @Furisto @tsturzl @YJDoc2 @tommady 
Hi! I'm currently working on this release blog and preparing for the release. Please let me know if there is anything you would like to include in the first release.

**Comment by Furisto** [comment]
@utam0k Can you share a draft of the blog article once you have it?

**Comment by yihuaf** [comment]
Super. Looking forward to this.

**Comment by utam0k** [comment]
> @utam0k Can you share a draft of the blog article once you have it?

@Furisto Sure. But I need more time to write this blog. I will prepare a blog in English and Japanese. Could you check my English?

**Comment by utam0k** [comment]
> Super. Looking forward to this.

Thanks. Do you want to see it before it will be published?

**Comment by utam0k** [comment]
> > Super. Looking forward to this.

@yihuaf 
Thanks. Do you want to see it before it will be published?

**Comment by yihuaf** [comment]
> > Super. Looking forward to this.
> 
> @yihuaf Thanks. Do you want to see it before it will be published?

Sure. I can help review it.

**Comment by Furisto** [comment]
See https://www.utam0k.jp/en/blog/2021/12/27/youki_first_release/
