### ISSUE TITLE
Dependencies issues for youki

### ISSUE THREAD

**Issue by unknowndevQwQ** [containers/youki#442]
I'm writing arch linux pkgbuild files for youki, and I recently noticed that elfutils and libseccomp have been added to youki's dependencies, and I noticed that runc and crun are also relying on them, but I'm not sure if youki only needs elfutils and libseccomp for build time

**Comment by yihuaf** [comment]
You will need libseccomp both for building and running. I think we only need elfutils for building, but I am not sure. The best way to to try it.

**Comment by yihuaf** [comment]
Please reopen if needed.
