### ISSUE TITLE
unsupported cgroup subsystem terminology style issues

### ISSUE THREAD

**Issue by unknowndevQwQ** [containers/youki#444]
https://github.com/containers/youki/blob/d35fb3ceb926debc59dfc5e90b64b73fd32db99e/crates/libcgroups/src/v1/manager.rs#L35

According to the description in https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#terminology, cgroup is never capitalized, but the output in the log is capitalized, should we consider changing it

**Comment by utam0k** [comment]
@unknowndevQwQ Are you interested working on this issue? If you don't have the time to fix it, I can fix it.

**Comment by unknowndevQwQ** [comment]
> @unknowndevQwQ Are you interested working on this issue? If you don't have the time to fix it, I can fix it.

I have time, but I am not familiar with English

**Comment by utam0k** [comment]
@unknowndevQwQ Don't worry. We'll support you ;)

**Comment by unknowndevQwQ** [comment]
@utam0k  offtopic: Can you create a telegram group for general questions and discussion?

**Comment by utam0k** [comment]
> @utam0k offtopic: Can you create a telegram group for general questions and discussion?

We have a discord group for the discussion and questions. How about this? There is the link of discord in README.md.

**Comment by unknowndevQwQ** [comment]
> > @utam0k offtopic: Can you create a telegram group for general questions and discussion?
> 
> We have a discord group for the discussion and questions. How about this? There is the link of discord in README.md.

Because electron, discord's client has unbearable lag in my case

**Comment by utam0k** [comment]
@unknowndevQwQ Can you use a browser?

**Comment by unknowndevQwQ** [comment]
> @unknowndevQwQ Can you use a browser?

It's not a good experience for me, maybe my computer is too slow

**Comment by utam0k** [comment]
I'm sorry, but I don't have the plan to create another community :cry: 
> It's not a good experience for me, maybe my computer is too slow

Maybe you can use this issue.
https://github.com/containers/youki/issues/10

**Comment by unknowndevQwQ** [comment]
> I'm sorry, but I don't have the plan to create another community cry
> 
> > It's not a good experience for me, maybe my computer is too slow
> 
> Maybe you can use this issue. #10

Ask a question about it in #10?
