### ISSUE TITLE
bug: youki does not run through docker when adding some flags

### ISSUE THREAD

**Issue by unknowndevQwQ** [containers/youki#453]
/etc/docker/daemon.json:
```
{
    "debug": true,
    "runtimes": {
        "runsc": {
            "path": "/usr/bin/runsc",
            "runtimeArgs": [
                "--debug",
                "--debug-log /tmp/docker-runsc"
            ]
        },
        "crun": {
            "path": "/usr/bin/crun",
            "runtimeArgs": [
                "--debug",
                "--log /tmp/docker-crun"
            ]
        },
        "youki": {
            "path": "/usr/bin/youki",
            "runtimeArgs": [
                "--log /tmp/docker-youki",
                "--log-format json"
            ]
        }
    }
}

```

run `sudo docker --debug --log-level debug run --runtime youki --rm hello-world`

```
DEBU[0000] [hijack] End of stdout                       
docker: Error response from daemon: failed to create shim: OCI runtime create failed: unable to retrieve OCI runtime error (open /var/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/8ed82eaee3e1042c9ca49e3f8a5d64d18f80b524317d1e5f070050fe612a5347/log.json: no such file or directory): /var/lib/docker/runtimes/youki did not terminate successfully: exit status 2: unknown.
```

**Comment by utam0k** [comment]
@unknowndevQwQ 
Thanks for your report! It may be a bug, however, I don't predict what kind of behavior you are expecting.
Please let me know the expected behavior if you want.

**Comment by unknowndevQwQ** [comment]
> @unknowndevQwQ Thanks for your report! It may be a bug, however, I don't predict what kind of behavior you are expecting. Please let me know the expected behavior if you want.

works fine and the corresponding flags work

**Comment by utam0k** [comment]
@unknowndevQwQ As far as I know,  `--log` and debug options aren't specified in the oci spec. However, youki has a similar feature, In the youki case, youki can change log level by using the environment variable. How about this?
https://github.com/containers/youki/blob/ac9639931ea65a60b238cf93fcc829ec12215af3/crates/youki/src/logger.rs#L9-L14

**Comment by utam0k** [comment]
Unify the discussion here.
https://github.com/containers/youki/issues/454
