### ISSUE TITLE
Feature request: add `--debug` flag to enable debug logging

### ISSUE THREAD

**Issue by unknowndevQwQ** [containers/youki#454]
It is useful to use youki as a model to observe some of the behavior of other OCI runtimes
Also this may help to find bugs in youki in the future

~~offtopic: I'm looking for the default folder location when runsc doesn't specify --root~~

**Comment by unknowndevQwQ** [comment]
It's probably more like runsc's --debug and --debug-log

**Comment by utam0k** [comment]
@unknowndevQwQ As far as I know, --log and debug options aren't specified in the oci spec. However, youki has a similar feature, In the youki case, youki can change log level by using the environment variable. How about this?

**Comment by unknowndevQwQ** [comment]
> @unknowndevQwQ As far as I know, --log and debug options aren't specified in the oci spec. However, youki has a similar feature, In the youki case, youki can change log level by using the environment variable. How about this?

Can you give an example?

**Comment by Furisto** [comment]
`
sudo YOUKI_LOG_LEVEL=debug youki create ...
`

**Comment by unknowndevQwQ** [comment]
> `sudo YOUKI_LOG_LEVEL=debug youki create ...`

How do I tell podman to pass the environment variable to youki?

**Comment by utam0k** [comment]
There may be no way to pass environment variables to podman. I have never used it that way.
I agree with adding the `--debug` option. How about making this option have the same behavior as `YOUKI_LOG_LEVEL=debug`?

**Comment by yihuaf** [comment]
It is probably easier to add `--debug` flag. `runc` has the same flag, even though it is not in the OCI spec. The option should have the same effect as `YOUKI_LOG_LEVEL=debug`.

**Comment by utam0k** [comment]
Ok, I decided to add it.
@unknowndevQwQ Why don't you try to implement it if you are interested in it? I believe it is not too difficult for the first contributor.

**Comment by unknowndevQwQ** [comment]
Sorry, I will most likely not have the free time to do this for some time in the future
Although this matter should not be too difficult

**Comment by utam0k** [comment]
@unknowndevQwQ Have you started implementing this feature? If not, I'll implement it.

**Comment by unknowndevQwQ** [comment]
> @unknowndevQwQ Have you started implementing this feature? If not, I'll implement it.

WIP
