### ISSUE TITLE
Support for SELinux label

### ISSUE THREAD

**Issue by utam0k** [containers/youki#469]
I don't know what we need. The first step is to identify what we need to do.
https://github.com/opencontainers/runtime-spec/blob/a3c33d663ebc56c4d35dbceaa447c7bf37f6fab3/config.md?plain=1#L213-L214

**Comment by YJDoc2** [comment]
I also found https://opensource.com/article/18/2/understanding-selinux-labels-container-runtimes, which is from the author who contributed to selinux go bindings for OCI : https://github.com/opencontainers/selinux

**Comment by utam0k** [comment]
@yihuaf Hi! Maybe are you interested?

**Comment by yihuaf** [comment]
I can try to do some investigation around this and see if I can come up with a design. Work starts to take up more time, so I may work slower than before.

**Comment by utam0k** [comment]
@yihuaf That's right. If you will be busy and it gets difficult, please let me know via discord DM or something. It's no problem at your own pace. THanks again, you're a big help 😍

**Comment by YJDoc2** [comment]
This is carried on in https://github.com/containers/youki/issues/2718
