### ISSUE TITLE
Flag `--log` is broken?

### ISSUE THREAD

**Issue by tiqwab** [containers/youki#475]
I found that the current youki can't write logs to a file.

```
$ sudo ./youki --log /tmp/youki.log create -b ~/workspace/tmp/mycontainer mycontainer

# file is created, but empty
$ ls -l /tmp/youki.log
-rw-r--r-- 1 root root 0 Nov 14 12:45 /tmp/youki.log
```

youki uses env_logger, but `env_logger::Target::Pipe` is broken according to https://github.com/env-logger-rs/env_logger/issues/208.

**Comment by Furisto** [comment]
I had noticed this too, but hoped that env_logger fixes this soon<sup>TM</sup>.

**Comment by yihuaf** [comment]
Hmm this is unfortunate... I was hoping `env_logger` to be more stable and save us the boilerplate. Let me take this issue and see if we should just revert to having our own logger implementation.
