### ISSUE TITLE
Folder /run/youki mode is not 0700

### ISSUE THREAD

**Issue by unknowndevQwQ** [containers/youki#481]
`sudo rm -Rf /run/youki && sudo podman --cgroup-manager cgroupfs --runtime /bin/youki --runtime-flag log=/tmp/youki.log run --rm hello-world && ls -ahl /run | grep youki`

```
...Previously omitted

drwxr-xr-x  2 root  root    40 11月 18 11:10 youki
```

youki version: 2120d33b8080d19

**Comment by utam0k** [comment]
Thanks for your report. Why is `0700` correct? Does runc or something work like it?

**Comment by unknowndevQwQ** [comment]
> Why is `0700` correct? Does runc or something work like it?

yep

**Comment by utam0k** [comment]
@unknowndevQwQ Would you like to try to fix it?

**Comment by utam0k** [comment]
@Szymongib Sure! I'll assign you.
