### ISSUE TITLE
determine_root_path() isn't quite right for XDG_RUNTIME_DIR and /run/user/{} cases

### ISSUE THREAD

**Issue by dgibson** [containers/youki#487]
For rootless operation, `determine_root_path()` will select from one of four options for the root state directory:

1. `$XDG_RUNTIME_DIR`
2. `/run/user/<uid>`
3. `$HOME/.youki/run`
4. `/tmp/youki/<uid>`

Options (1) and (2) will often amount to the same thing, since `/run/user/<uid>` is the default value for `$XDG_RUNTIME_DIR` on most systems.  But, in both these cases we don't include "youki", or a similar tag in the path at all, so state directories for each container will be placed directly underneath the runtime directory.

That doesn't match normal conventions, where each program puts its own subdir under the runtime dir.  More importantly, it means that `youki list` which works by iterating through the subdirectories of the root dir will list unrelated things from other tools as though they were containers.

**Comment by utam0k** [comment]
@dgibson Thanks for your report. Your point is here, right?
https://github.com/containers/youki/blob/e766310a899fac41766c3e6589fb68f84ac17793/crates/youki/src/main.rs#L136-L174
I didn't know the normal convention.

**Comment by dgibson** [comment]
> @dgibson Thanks for your report. The part you pointed out is here, right?

Yes, that's it.

> I didn't know the normal convention.

I should clarify - I don't have some special knowledge here, I just looked at what's in that directory on my system, and it appears to be subdivided by the program using it:

```
$ ls /run/user/1000
bus=         dconf/          doc/    gvfs/   gvfsd-sftp/  ICEauthority  pipewire-0=      pulse/  systemd/
claws-mail/  discord-ipc-0=  gnupg/  gvfsd/  i3/          keyring/      pipewire-0.lock  runc/
```
