### ISSUE TITLE
Command line parsing front end would be useful in its own crate

### ISSUE THREAD

**Issue by dgibson** [containers/youki#508]
Some colleagues and I have a use case for a rather specialized OCI runtime tool.  The idea is that it wouldn't implement the container backend itself, but rather would just be a frontend which then calls into another implementation to do the actual container operations.  We have a couple of uses in mind for this:

- Instrumenting / tracing an existing runtime for debugging purposes
- Translating the OCI command line interface into semantically similar, but not identical interfaces (e.g. the shimv2 gRPC protocol used by Kata containers v2)

We were planning to make this in Rust, and youki already has a very clean command line parsing implementation that is not deeply tied into the back end implementation.  Would it be ok to split the front end CLI parsing into a separate crate, which we could re-use for our purposes?

/cc @c3d

**Comment by Furisto** [comment]
Seems reasonable. We have done similar things with other parts of our code in the past, as one of our goals is to make it easier to write container implementations in Rust, so there is no conflict there. The required changes seem to be relatively low impact.

**Comment by dgibson** [comment]
> Seems reasonable. We have done similar things with other parts of our code in the past, as one of our goals is to make it easier to write container implementations in Rust, so there is no conflict there. The required changes seem to be relatively low impact.

Terrific!  I've made a suggested implementation of this change in PR #509

**Comment by utam0k** [comment]
@dgibson 
Furisto is right and I agree with him. Are you talking about kata-agent?
https://github.com/kata-containers/kata-containers/pull/2785
I had heard a bit of this story before. Let's move forward cooperatively. Thank you very much for your contribution to youki :100:

**Comment by dgibson** [comment]
> @dgibson Furisto is right and I agree with him. Are you talking about kata-agent? [kata-containers/kata-containers#2785](https://github.com/kata-containers/kata-containers/pull/2785) I had heard a bit of this story before. Let's move forward cooperatively. Thank you very much for your contribution to youki 100

Actually, no.  I'm aware of that PR, and re-using the command line parsing there as well could certainly be useful, but it's not something I'm looking at myself.  Rather I'm looking at adding an OCI command line to the full Kata stack, with runtime, VM and agent.  Currently Kata (2.x) is controlled using the "shimv2" gRPC protocol which has similar operations to the OCI runtime spec, but with a few differences.  That means that Kata 2.x can't be used with podman, for example, only engines which speak the shimv2 protocol (containerd and CRI-O both have such support).

We're aiming to restore the ability to use Kata with podman by making a wrapper which interprets the OCI command line and implements it using a shimv2 backend like Kata.
