### ISSUE TITLE
Support for containerd

### ISSUE THREAD

**Issue by utam0k** [containers/youki#531]
# Goal

Pass the integration test of contained

# Status
Done!

### How to run containerd's integration test with youki

https://containers.github.io/youki/developer/containerd_integration_test_using_youki.html

**Comment by guni1192** [comment]
@utamk0
What is the status of this issue?
I am doing containerd integration tests with runc replaced by youki.
Do you need the procedure and results of the test in my local environment?

**Comment by utam0k** [comment]
@guni1192 I would love to have it. Can you please do it? Or can you give me a PR with a shell of the test means?

**Comment by guni1192** [comment]
OK.　First, I will share the results of the test conducted in my environment.
I published it on my Gist because the lines in the log are very long.

https://gist.github.com/guni1192/af931310dca8dfc5b2a0f5b79acbad32

**Comment by guni1192** [comment]
@utam0k 
I would like to go through the steps to automate integration testing using PR.
Can I edit the Vagrantfile in the repository for this purpose?
Specifically, I want to set up containerd and golang.
If you don't mind, I would like to send a PR this week.

**Comment by guni1192** [comment]
I am concerned about a number of failed test cases in the containerd integration test, as follows.
I think containerd may have used runc-specific options( `runc kill --all <CONTAINER_ID> <SIGNAL>` ).

```
=== RUN   TestDaemonRestart
    container_test.go:2042: failed to delete task: unknown error after kill: runc did not terminate successfully: exit status 2: error: Found argument '--all' which wasn't expected, or isn't valid in this context
        
        	If you tried to supply `--all` as a value rather than a flag, use `-- --all`
        
        USAGE:
            runc kill <CONTAINER_ID> <SIGNAL>
        
        For more information try --help
        : unknown
--- PASS: TestDaemonRestart (0.31s)
=== RUN   TestContainerKillInitKillsChildWhenNotHostPid
    container_test.go:2199: unknown error after kill: runc did not terminate successfully: exit status 2: error: Found argument '--all' which wasn't expected, or isn't valid in this context
        
        	If you tried to supply `--all` as a value rather than a flag, use `-- --all`
        
        USAGE:
            runc kill <CONTAINER_ID> <SIGNAL>
        
        For more information try --help
        : unknown
--- FAIL: TestContainerKillInitKillsChildWhenNotHostPid (0.35s)
```

```
 $ runc kill --help                                                                                                                                                                                     
NAME:
   runc kill - kill sends the specified signal (default: SIGTERM) to the container's init process

USAGE:
   runc kill [command options] <container-id> [signal]

Where "<container-id>" is the name for the instance of the container and
"[signal]" is the signal to be sent to the init process.

EXAMPLE:
For example, if the container id is "ubuntu01" the following will send a "KILL"
signal to the init process of the "ubuntu01" container:

       # runc kill ubuntu01 KILL

OPTIONS:
   --all, -a  send the specified signal to all processes inside the container
   

```

**Comment by utam0k** [comment]
> @utam0k Next, I would like to PR the procedure for automating containerd integration testing. Can I edit the Vagrantfile in the repository for this purpose? Specifically, I want to set up containerd and golang. If you don't mind, I would like to send a PR this week.

Sure, Let's do it. Probably this will help you.
https://github.com/containers/youki/pull/514/commits/4492752ed13b802e1fcdf617944936012ee2da61

**Comment by utam0k** [comment]
> I am concerned about a number of failed test cases in the containerd integration test, as follows. I think containerd may have used runc-specific options( `runc kill --all <CONTAINER_ID> <SIGNAL>` ).
> 
> ```
> === RUN   TestDaemonRestart
>     container_test.go:2042: failed to delete task: unknown error after kill: runc did not terminate successfully: exit status 2: error: Found argument '--all' which wasn't expected, or isn't valid in this context
>         
>         	If you tried to supply `--all` as a value rather than a flag, use `-- --all`
>         
>         USAGE:
>             runc kill <CONTAINER_ID> <SIGNAL>
>         
>         For more information try --help
>         : unknown
> --- PASS: TestDaemonRestart (0.31s)
> === RUN   TestContainerKillInitKillsChildWhenNotHostPid
>     container_test.go:2199: unknown error after kill: runc did not terminate successfully: exit status 2: error: Found argument '--all' which wasn't expected, or isn't valid in this context
>         
>         	If you tried to supply `--all` as a value rather than a flag, use `-- --all`
>         
>         USAGE:
>             runc kill <CONTAINER_ID> <SIGNAL>
>         
>         For more information try --help
>         : unknown
> --- FAIL: TestContainerKillInitKillsChildWhenNotHostPid (0.35s)
> ```
> 
> ```
>  $ runc kill --help                                                                                                                                                                                     
> NAME:
>    runc kill - kill sends the specified signal (default: SIGTERM) to the container's init process
> 
> USAGE:
>    runc kill [command options] <container-id> [signal]
> 
> Where "<container-id>" is the name for the instance of the container and
> "[signal]" is the signal to be sent to the init process.
> 
> EXAMPLE:
> For example, if the container id is "ubuntu01" the following will send a "KILL"
> signal to the init process of the "ubuntu01" container:
> 
>        # runc kill ubuntu01 KILL
> 
> OPTIONS:
>    --all, -a  send the specified signal to all processes inside the container
>    
> ```

@guni1192 Thanks for your analytics. It may be a contributing chance to the runtime spec! But for new youki doesn't support this option, we have to support it.

**Comment by kzys** [comment]
Thanks @guni1192 and @utam0k!

# The lack of `--all`
* TestTaskForceDelete
* TestContainerKillInitKillsChildWhenNotHostPid
* TestContainerKill
* TestTaskForceDelete

# pid/user namespace?
* TestContainerKillInitPidHost
* TestUserNamespaces

# containerd flakiness?
* TestRestartMonitor - This test is new. So it may be more about containerd, less about youki.

# Unknown
* TestShimDoesNotLeakPipes
* TestContainerNoBinaryExists
* TestContainerExecNoBinaryExists
* TestRegressionIssue6429

**Comment by kzys** [comment]
I've updated the comment above. Some of them are actually working for me.

It would be better to run the tests in GitHub Actions first even if some of them are failing. So that we could agree which tests are actually failing.

**Comment by utam0k** [comment]
latest results
```consol
root@ubuntu2204:~/go/src/github.com/containerd/containerd# cat result.txt | grep "FAIL"
--- FAIL: TestContainerKillInitPidHost (2.66s)
--- FAIL: TestContainerKillInitKillsChildWhenNotHostPid (0.15s)
--- FAIL: TestContainerExecLargeOutputWithTTY (0.37s)
--- FAIL: TestContainerMetrics (0.46s)
--- FAIL: TestContainerKill (0.83s)
--- FAIL: TestContainerExecNoBinaryExists (1.07s)
--- FAIL: TestUserNamespaces (6.44s)
    --- FAIL: TestUserNamespaces/WritableRootFS (5.43s)
    --- FAIL: TestUserNamespaces/ReadonlyRootFS (1.01s)
```

**Comment by utam0k** [comment]
@YJDoc2 Have you ever encountered [TestWaitStoppedProcess](https://github.com/containerd/containerd/blob/e61539ae84cd5af381fca5f685af7c77520adcc1/integration/client/container_test.go#L912) during doing #1252 
I guess it is related to the output of the log problem you told me.

```console
root@ubuntu2204:~/go/src/github.com/containerd/containerd# make TEST_RUNTIME=io.containerd.runc.v2 TESTFLAGS="-timeout 120m -run TestWaitStoppedProcess" integration                                                                                               
+ integration                                                                                                                                                                                                                                                                               
INFO[0000] running tests against containerd              revision=3df54a852345ae127d1fa3092b95168e4a88e2f8 runtime=io.containerd.runc.v2 snapshotter= version=v1.5.11                
INFO[0000] start to pull seed image                      image="ghcr.io/containerd/busybox:1.32"                                                                                                                                                                                            
=== RUN   TestWaitStoppedProcess                                                                                                                                                                                                                                                            
=== PAUSE TestWaitStoppedProcess                                                                                                                                                                                                                                                            
=== CONT  TestWaitStoppedProcess                                                                                                                                                                                                                                                            
    container_test.go:967: OCI runtime exec failed: unable to retrieve OCI runtime error (invalid character ':' looking for beginning of value): runc did not terminate successfully: exit status 6: unknown                                                                                
--- FAIL: TestWaitStoppedProcess (0.07s)                                                                                                                                                                                                                                                    
FAIL  
```

**Comment by YJDoc2** [comment]
@utam0k Have you tried `TestWaitStoppedProcess` with the #1252 ? I tried it with changes of that PR, and it seem to pass without any issues.

**Comment by utam0k** [comment]
> @utam0k Have you tried `TestWaitStoppedProcess` with the #1252 ? I tried it with changes of that PR, and it seem to pass without any issues.

Okay, I'll check it. Thanks

**Comment by YJDoc2** [comment]
With merge of #1204 , I think only one or two of the  tests are still failing, I will check later and update which ones are failing.

**Comment by YJDoc2** [comment]
The reason TestContainerKill is failing is because the way it checks for error here https://github.com/containerd/containerd/blob/main/pkg/process/utils.go#L135 is by string comparison of error message (mostly) , and as youki's error message is different from what is checked, it assumes that an "incorrect" error was given and fails the test. Simply changing the error message to match one of the comparison passes the test. However, I'd prefer not to change the error message that is given, as I feel youki's error message is contains more information helpful for debugging. Maybe we can add that string after the current error message, or I'm looking how we can pass the ESRCH comparison, as I feel that would be a better way

**Comment by YJDoc2** [comment]
It would appear that with latest main (d99b665283f06b827a8762dc05a4b96e3a98a0df) we are passing all the tests * :tada: :tada: :tada: 

\* The tests themselves seem to be flaky, I ran the whole suit 3 times before every tests passed. The ones that failed in first 2 passed when run individually, and in the 3rd run every all of the tests passed!

**Comment by YJDoc2** [comment]
This is now completed with the merge of #968 !
