### ISSUE TITLE
Using youki and containerd to run Kubernetes

### ISSUE THREAD

**Issue by utam0k** [containers/youki#585]
## Goals

- [ ] Anyway, to be able to create a simple pod
- [ ] Integrate containerd integration test into youki CI
- [ ] Pass the containerd integration test.
- [ ] Add the documentation how to run

**Comment by utam0k** [comment]
@yihuaf @tsturzl Hi! Are you interested in this issue? This could be quite interesting.

**Comment by tsturzl** [comment]
I'd be interested in working on this.

**Comment by utam0k** [comment]
> I'd be interested in working on this.

@tsturzl 
Thanks for your reaction. I'm glad to hear of your intention. I'll assign you to this issue.
BTW I am working on integrating the contained integration test into youki CI. https://github.com/containers/youki/pull/514
This is the only one I'll do.

**Comment by utam0k** [comment]
Hi, @inductor Are you interested in this issue?

**Comment by utam0k** [comment]
Dup https://github.com/containers/youki/issues/531
