### ISSUE TITLE
podman runtime specify youki create container Error

### ISSUE THREAD

**Issue by wyaow** [containers/youki#594]
version
Linux version 3.10.0-957.el7.x86_64
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018
podman version 1.6.4

youki version 0.0.1
commit: 0.0.1-0-91b7632
..............................................................................................................
[root@localhost local]# podman --runtime /usr/local/youki run -d --name niginx -p 80:80 xx.xxxxx.com/nginx
Error: container 53ae3c4eefef6b261f9dcf9d361dbdab11e5df675841320dd8214cc0239a2dd7 does not exist.
ERRO[0000] Error removing container 53ae3c4eefef6b261f9dcf9d361dbdab11e5df675841320dd8214cc0239a2dd7 from runtime after creation failed 
Error: [WARN crates/libcontainer/src/rootfs/mount.rs:253] 2022-01-04T22:50:46.267528492-05:00 Could not mount "net_cls,net_prio" cgroup subsystem
[WARN crates/libcontainer/src/rootfs/mount.rs:253] 2022-01-04T22:50:46.269389430-05:00 Could not mount "cpu,cpuacct" cgroup subsystem
[WARN crates/libcontainer/src/process/container_init_process.rs:140] 2022-01-04T22:50:46.284662733-05:00 masked path "/proc/latency_stats" not exist
[WARN crates/libcontainer/src/syscall/linux.rs:139] 2022-01-04T22:50:46.315288377-05:00 CAP_PERFMON is not supported.
[WARN crates/libcontainer/src/syscall/linux.rs:139] 2022-01-04T22:50:46.315326696-05:00 CAP_BPF is not supported.
Error: failed to create container
Caused by:
    0: failed to wait for init ready
    1: failed to wait for init ready
    2: channel connection broken: OCI runtime error
..............................................................................................................
tks much.

**Comment by Furisto** [comment]
@wyaow Can you post the output of youki info?

**Comment by wyaow** [comment]
[root@localhost local]# youki info
Version           0.0.1
Kernel-Release    3.10.0-957.el7.x86_64
Kernel-Version    #1 SMP Thu Nov 8 23:39:32 UTC 2018
Architecture      x86_64
Operating System  CentOS Linux 7 (Core)
Cores             4
Total Memory      7821
Cgroup setup      legacy
Cgroup mounts
  blkio           /sys/fs/cgroup/blkio
  cpu             /sys/fs/cgroup/cpu,cpuacct
  cpuacct         /sys/fs/cgroup/cpu,cpuacct
  cpuset          /sys/fs/cgroup/cpuset
  devices         /sys/fs/cgroup/devices
  freezer         /sys/fs/cgroup/freezer
  hugetlb         /sys/fs/cgroup/hugetlb
  memory          /sys/fs/cgroup/memory
  net_cls         /sys/fs/cgroup/net_cls,net_prio
  net_prio        /sys/fs/cgroup/net_cls,net_prio
  perf_event      /sys/fs/cgroup/perf_event
  pids            /sys/fs/cgroup/pids
Namespaces        enabled
  mount           enabled
  uts             enabled
  ipc             enabled
  user            enabled
  pid             enabled
  network         enabled
  cgroup          enabled

**Comment by tsturzl** [comment]
@wyaow I don't believe CentOS 7 satisfies the appropriate version for libseccomp either.

You can check with this simple script to see if you have the appropriate version of libseccomp: `pkg-config --atleast-version=2.5 libseccomp && echo "good" || echo "bad"`

**Comment by jhult** [comment]
Here is a good overview of packaging for `libseccomp` for various OSes: https://repology.org/project/libseccomp/versions

**Comment by utam0k** [comment]
@wyaow Youki needs a linux kernel version of 5.4 or later 😭

**Comment by wyaow** [comment]
@utam0k tks you anyway, I guess it would be better to note on README.
@tsturzl actually i tried it on an other Centos8 (Linux Kerner of 4.18 with libseccomp.so.2.5.1) os, it was same.
