### ISSUE TITLE
Revert back to saving full config.json instead of youki config

### ISSUE THREAD

**Issue by Furisto** [containers/youki#609]
We introduced a lightweight version of the config.json a while ago in order to improve performance. This broke youki exec however as exec is still looking for the full config.json. Given that we need a lot of the stuff in config.json for exec and that it would also mean that ContainerBuilderImpl would need to be split up into an init and exec part if we want to keep the current way (because they would need to use different configs) should we revert back to the full config.json?

@utam0k

**Comment by gattytto** [comment]
in my use case I have kubernetes with cri-o:
```bash
[crio.runtime.runtimes.youki]
runtime_path = "/usr/bin/strace-youki.sh"
runtime_type = "oci"
runtime_root = "/run/youki"
```

maybe you could use the state.json file which has a bundle field
```bash
"bundle":"/run/containers/storage/overlay-containers/89d091a03dfdf8738736b4a02e42365d05d6732f0fab979f66b513afa2bf8340/userdata"
```
then in that path /config.json has the full thing.

**Comment by utam0k** [comment]
@Furisto 
Ok, Let's revert to https://github.com/containers/youki/pull/447 this time once. However, the performance will probably go down. So you will need to inspect and improve the performance.

**Comment by gattytto** [comment]
@utam0k maybe you can pull it from the state only when exec is called so you don't affect the rest of the operations

**Comment by utam0k** [comment]
> maybe you can pull it from the state only when exec is called so you don't affect the rest of the operations

I think we need to organize what the exec command needs from the original config(`config.json`). And we may need to make some major code change to apply them. Either way, It's not that easy.

**Comment by YJDoc2** [comment]
Hey @Furisto can you link which specific part of exec will face issue, or the builder impl will need to be split ? I am kind of lost where the issue would be :sweat_smile: 
According to how the config issue is there, maybe one option can be adding the path of config.json in the YoukiConfig, and in the part which needs the full config, loading it using this path? Adding a single path string should not give too much overhead, compared to switching back to full config.
