### ISSUE TITLE
Add CODE-OF-CONDUCT.md and SECURITY.md

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/youki#62]
Please add a CODE-OF-CONDUCT.md and SECURITY.md to this project.  Feel free to cut/paste the ones from https://github.com/containers/buildah and then just touch up the project name within.  Also, please include a contact email in the README.md if possible so that we can send any security issues to it.

**Comment by utam0k** [comment]
@TomSweeneyRedHat It would certainly be nice to have. Can I ask you to review the PR that I will make?

**Comment by TomSweeneyRedHat** [comment]
Certainly, I'd be happy to @utam0k !

**Comment by utam0k** [comment]
@TomSweeneyRedHat 
It's a big help! I have to work during the week so I can't get much time, but I will have the PR ready by this weekend.
