### ISSUE TITLE
need rust shim

### ISSUE THREAD

**Issue by timchenxiaoyu** [containers/youki#633]
replace go shim  memory friendly。

shim is long run ，so rust shim is urgently needed

**Comment by utam0k** [comment]
@timchenxiaoyu Thanks for your report. I'm sorry but I couldn't understand what you want me to do. Please tell me more concrete explanation?

**Comment by harche** [comment]
@timchenxiaoyu https://github.com/containers/conmon-rs

**Comment by timchenxiaoyu** [comment]
@utam0k 
![image](https://user-images.githubusercontent.com/9782796/155318312-5b2b0b17-3fe3-4638-8a65-4dedf0d81c73.png)

rust implement

**Comment by utam0k** [comment]
@timchenxiaoyu Maybe is this it, by any chance?
https://github.com/containerd/rust-extensions/pull/22

**Comment by utam0k** [comment]
> @timchenxiaoyu https://github.com/containers/conmon-rs

@harche 
Thank you for trying to help. I appreciate it.

**Comment by harche** [comment]
> > @timchenxiaoyu https://github.com/containers/conmon-rs
> 
> @harche Thank you for trying to help. I appreciate it.

CRI-O uses https://github.com/containers/conmon right now, and the rust version is getting developed at https://github.com/containers/conmon-rs

**Comment by timchenxiaoyu** [comment]
Thank you ！！！ @utam0k @utam0k
