### ISSUE TITLE
Failed to create container when using relative root path

### ISSUE THREAD

**Issue by Szymongib** [containers/youki#720]
When using youki with relative root path creating container fails. From looking at a code it is probably due to not converting path to absolute path and using `chdir`.

Steps to reproduce:
```
mkdir -p ./some/dir
./youki --root ./some/dir create -b [BUNDLE] some-id
```
Error: `Error: No such file or directory`

I can look into it and try to fix it.

**Comment by utam0k** [comment]
@Szymongib First of all, thanks for your report. Can I leave it to you?
