### ISSUE TITLE
Support for rootless container

### ISSUE THREAD

**Issue by utam0k** [containers/youki#77]
I don't know anything about rootless container yet. I'd like to use this issue to gather references and think about the design. I'm also looking for people to challenge this.

# References
- https://github.com/opencontainers/runc/blob/master/rootless_linux.go
- https://rootlesscontaine.rs/
- https://docs.docker.com/engine/security/rootless/

**Comment by Furisto** [comment]
I am interested in looking into this.

**Comment by utam0k** [comment]
@Furisto 
I will assign you to this issue.
However, I don't know how big this issue will be. Where would you like to start? You can start with the implementation, but I don't know yet if youki have what it takes to implement it.

**Comment by Furisto** [comment]
@utam0k 
We will need to delegate the creation of the cgroups to systemd. That effort is luckily already underway. We also need to use user namespaces and uid and guidmaps to map the root user to a non root user on the host. I need to read up on the details.

**Comment by utam0k** [comment]
@Furisto 
This is https://github.com/containers/youki/pull/46, isn't it?
> We will need to delegate the creation of the cgroups to systemd. That effort is luckily already underway. 
I'm willing to start where you can start implementing outside of this PR, but do you want to start a challenge.

**Comment by Furisto** [comment]
@utam0k Yes, correct.

**Comment by utam0k** [comment]
@Furisto 
I'm willing to start where you can start implementing outside of this PR. Do you want to start a challenge?

**Comment by Furisto** [comment]
@utam0k Yeah, I am planning to work on the necessary adaptations for the create command this weekend.

**Comment by Furisto** [comment]
Update: I can now create a container without being root and map root inside the container to a non root user on the host. I am still investigating problems with bind mounts and getting a shell into the container.

**Comment by chenyukang** [comment]
I'm following the README, the this command will trigger error with message: 

```bash
$ curl https://gist.githubusercontent.com/utam0k/8ab419996633066eaf53ac9c66d962e7/raw/e81548f591f26ec03d85ce38b0443144573b4cf6/config.json -o config.json
$ cd ../
$ ./youki create -b tutorial tutorial_container
$ ./youki state tutorial_container # You can see the state the container is in as it is being generate.
$ ./youki start tutorial_container
$ ./youki state tutorial_container # Run it within 5 seconds to see the running container.
$ ./youki delete tutorial_container # Run it after the container is finished running.
```

```
yukang@mango:~/youki$ ./youki create -b demo demo_container
[DEBUG src/container/init_builder.rs:90] 2021-08-23T13:59:59.138549106+00:00 container directory will be "/run/user/1001/demo_container"
[DEBUG src/container/container.rs:94] 2021-08-23T13:59:59.189015677+00:00 Save container status: Container { state: State { oci_version: "v1.0.2", id: "demo_container", status: Creating, pid: None, bundle: "demo", annotations: Some({}), created: None, creator: None, use_systemd: None }, root: "/run/user/1001/demo_container" } in "/run/user/1001/demo_container"
[DEBUG src/rootless.rs:34] 2021-08-23T13:59:59.189315080+00:00 rootless container should be created
[WARN src/rootless.rs:35] 2021-08-23T13:59:59.189352980+00:00 resource constraints and multi id mapping is unimplemented for rootless containers
Error: rootless containers require gid_mappings in spec
```

**Comment by chenyukang** [comment]
Do we need to update the config.json for the rootless container?

**Comment by Furisto** [comment]
@chenyukang Yes, the current spec does not work for rootless containers. Are you interested in fixing it?

**Comment by chenyukang** [comment]
I'm interested in fixing it.
But I'm still trying to understand the code since this is my first try at it. :)

**Comment by yihuaf** [comment]
I think `runc` has `runc spec --rootless`. Maybe that's what we should add. @chenyukang Would you like to add it? If so, just create a new issue and ping us if you need any help.

**Comment by chenyukang** [comment]
Thanks @yihuaf , I use `runc spec --rootless` to generate a config.json, we need to add this to config.json: 

```json
  "uidMappings": [
      {
        "containerID": 0,
        "hostID": 1001,
        "size": 1
      }
    ],
    "gidMappings": [
      {
        "containerID": 0,
        "hostID": 1001,
        "size": 1
      }
    ],
```

Should we add a demo config.json to repo, maybe add a directory youki_integration_test/config/,...

Currently, we use a gist in README.md, or do I create a gist and fix readme?

**Comment by utam0k** [comment]
> Thanks @yihuaf , I use `runc spec --rootless` to generate a config.json, we need to add this to config.json:
> 
> ```json
>   "uidMappings": [
>       {
>         "containerID": 0,
>         "hostID": 1001,
>         "size": 1
>       }
>     ],
>     "gidMappings": [
>       {
>         "containerID": 0,
>         "hostID": 1001,
>         "size": 1
>       }
>     ],
> ```
> 
> Should we add a demo config.json to repo, maybe add a directory youki_integration_test/config/,...
> 
> Currently, we use a gist in README.md, or do I create a gist and fix readme?

When I made this tutorial, there was no spec command yet, so I used gist. Now that the spec command available, I think it would be a good idea to create a tutorial based on it.

**Comment by yihuaf** [comment]
@chenyukang Yes, we need to add uid, gid mapping and user namespace to the spec. And I agree we should change the readme tutorial to be use `youki spec` and `youki spec --rootless`. I'd rather not copy around snippets if we can avoid it. Just a heads up, there are some cases of rootless Youki is not working quite right yet.

**Comment by chenyukang** [comment]
yes, I will fix the readme with `youki spec`. 
`youki spec --rootless` is not available right now. We need to add it. 
After that add another `rootless` demo in the tutorial.

**Comment by utam0k** [comment]
> yes, I will fix the readme with `youki spec`.
> `youki spec --rootless` is not available right now. We need to add it.
> After that add another `rootless` demo in the tutorial.

@chenyukang 
This is a very wonderful initiative. If you'd like, could you create an issue with this?

**Comment by chenyukang** [comment]
> I was trying to fix this issue. Can you now try again with tip of the tree? As long as the spec has user namespace, you should be able to run rootless, sudo or not. There are likely still issue with it, but it should run now.

I merged code from master, the are still an error, the last one is `Failed to add tasks to cgroup manager`

```
[DEBUG src/container/builder_impl.rs:103] 2021-08-27T23:39:39.428075772+00:00 init pid is Pid(2333737)
Error: Failed to add tasks to cgroup manager

Caused by:
    Permission denied (os error 13)
```

**Comment by yihuaf** [comment]
Yea, and your rootfs will be toasted lol. I just discovered this today as
well and I have a PR out. I will let you know when it is merged. As I said
before, rootless is not quite working yet. My first goal is to pass as many
integration tests as possible. And then we can go about fixing all the
corner cases. You are welcome to start fixing if you notice any issue. Feel
free to start filing issues on this area.
