### ISSUE TITLE
Linker error when building youki with the build.sh script

### ISSUE THREAD

**Issue by RMPR** [containers/youki#772]
Youki build fails with the error message:

```shell
  = note: /usr/bin/ld: cannot find -lm
          /usr/bin/ld: cannot find -lc
          collect2: error: ld returned 1 exit status
```

OS: Fedora 35
Kernel: 5.16.11-200
Arch: x86_64
SELinux status: permissive

**Comment by utam0k** [comment]
Please re-open if anything else comes up.

**Comment by RMPR** [comment]
I commented on the linked PR.
