### ISSUE TITLE
rust checkpoint integration tests fail on kernel version 5.11

### ISSUE THREAD

**Issue by YJDoc2** [containers/youki#814]
In my system the checkpointing tests fail, even though those are passing in the CI. This might be due to kernel not compiled with support for checkpointing , or some other issues. If this is a support issue, then the tests should be put behind conditional tests, which will check the support. In any case the error message should be changed to include the file name which it is trying to read, so the error can be better uderstood when encountered.

Update :
Modify test to copy the log file in case of failure

Error message :
```
3 / 7 : checkpoint and leave running with --work-path /tmp : not ok
        Error :
stdout :
stderr : Error: failed to checkpoint container 558aea4b-ece9-a4a3-eada-40afee9f28ca

Caused by:
    checkpointing container 558aea4b-ece9-a4a3-eada-40afee9f28ca failed with Os { code: 2, kind: NotFound, message: "No such file or directory" }. Please check CRIU logfile /tmp//dump.log

4 / 7 : checkpoint and leave running : not ok
        Error :
stdout :
stderr : Error: failed to checkpoint container 558aea4b-ece9-a4a3-eada-40afee9f28ca

Caused by:
    checkpointing container 558aea4b-ece9-a4a3-eada-40afee9f28ca failed with Os { code: 2, kind: NotFound, message: "No such file or directory" }. Please check CRIU logfile /tmp/fef46b54-651d-49b8-ef89-bca5dd998f8a/checkpoint/dump.log

```

System info :
```
Version           0.0.2
Commit            f66d389
Kernel-Release    5.11.0-49-generic
Kernel-Version    #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022
Architecture      x86_64
Operating System  Ubuntu 21.04
Cores             8
Total Memory      7859
Cgroup setup      hybrid
Cgroup mounts
  blkio           /sys/fs/cgroup/blkio
  cpu             /sys/fs/cgroup/cpu,cpuacct
  cpuacct         /sys/fs/cgroup/cpu,cpuacct
  cpuset          /sys/fs/cgroup/cpuset
  devices         /sys/fs/cgroup/devices
  freezer         /sys/fs/cgroup/freezer
  hugetlb         /sys/fs/cgroup/hugetlb
  memory          /sys/fs/cgroup/memory
  net_cls         /sys/fs/cgroup/net_cls,net_prio
  net_prio        /sys/fs/cgroup/net_cls,net_prio
  perf_event      /sys/fs/cgroup/perf_event
  pids            /sys/fs/cgroup/pids
  unified         /sys/fs/cgroup/unified
CGroup v2 controllers
  cpu             detached
  cpuset          detached
  hugetlb         detached
  io              detached
  memory          detached
  pids            detached
  device          attached
Namespaces        enabled
  mount           enabled
  uts             enabled
  ipc             enabled
  user            enabled
  pid             enabled
  network         enabled
```

**Comment by utam0k** [comment]
Thanks for rising the issue. I've same trouble too.

**Comment by utam0k** [comment]
@adrianreber If you know something, please help us 🙏

**Comment by adrianreber** [comment]
Can the criu log file be attached to this issue? I was always developing with newer kernels than mentioned here.

**Comment by adrianreber** [comment]
Tests are also working on my system with 5.16.16-200.fc35.x86_64

**Comment by utam0k** [comment]
Here are the integration test results on my local. But I couldn't find the dump.log because after running the integration tests, I couldn't find the dump file.
```console
# Start group lifecycle
1 / 7 : create : ok
2 / 7 : start : ok
3 / 7 : checkpoint and leave running with --work-path /tmp : not ok
        Error :
stdout : 
stderr : Error: failed to checkpoint container b98f4c74-3757-e59f-13ba-cb1b9a4dcbb8

Caused by:
    checkpointing container b98f4c74-3757-e59f-13ba-cb1b9a4dcbb8 failed with "CRIU RPC request failed with (message:Error (criu/net.c:643): Unsupported link 2 (type 768 kind ipip)\n error:0". Please check CRIU logfile /tmp//dump.log

4 / 7 : checkpoint and leave running : not ok
        Error :
stdout : 
stderr : Error: failed to checkpoint container b98f4c74-3757-e59f-13ba-cb1b9a4dcbb8

Caused by:
    checkpointing container b98f4c74-3757-e59f-13ba-cb1b9a4dcbb8 failed with "CRIU RPC request failed with (message:Error (criu/net.c:643): Unsupported link 2 (type 768 kind ipip)\n error:0". Please check CRIU logfile /tmp/a5599acf-f57e-4741-b33a-4cbb6be5e0ca/checkpoint/dump.log
```

**Comment by adrianreber** [comment]
Any idea what link ipip is? In the criu message. There is some kind of unsupported network link on your system.

**Comment by adrianreber** [comment]
Both log files as mentioned in the output do not exist? Could you verify that they are not cleaned up by the tests suite.

**Comment by utam0k** [comment]
I couldn't find them 😭 I'll check.
> Both log files as mentioned in the output do not exist? Could you verify that they are not cleaned up by the tests suite.

I don't have idea. hmm...
> Any idea what link ipip is? In the criu message. There is some kind of unsupported network link on your system.

@YJDoc2 Did you encounter same errors?

**Comment by YJDoc2** [comment]
Hey, sorry for late reply

I think my error was different... my error message is in the issue comment itself
>@YJDoc2 Did you encounter same errors?

Yes, currently the test framework deletes all the container files ones the tests are done. I have an improvement for this test in mind which can copy the log file if failed, but I am a bit busy today, so will try to get the file and send here tomorrow or day after tomorrow.
> I couldn't find them I'll check.

**Comment by YJDoc2** [comment]
Hey, so I looked into it, and it appears that the dump file itself is probably not getting created. I tried to open the path from the container checkpoint function itself, where we set the logfile path in the error message, but it is showing that the path is invalid in that function itself.

As far as I have traced the execution, it seems to work fine till https://github.com/containers/youki/blob/main/crates/libcontainer/src/container/container_checkpoint.rs#L106 ; at which point it calls criu.dump() which returns the error result. 

The error that is returned is `File not found`, so it appears that the library is attempting to read/write some file which does not exist. As `rust-criu` is an external crate to the project,I cannot trace execution in it by printlns or other ways, as cargo does not trigger re-compilations of those.

Just by looking at the code, criu.dump() calls do_swrk_with_response(), in which file read/write operations at https://github.com/adrianreber/rust-criu/blob/main/src/lib.rs#L105 and  https://github.com/adrianreber/rust-criu/blob/main/src/lib.rs#L110 so there might be a chance that it is failing at some of this points, but can be somewhere else too.

It feels like my and @utam0k 's system set-up and this library's expectations of the set-up are clashing somewhere, because of which the error is occurring. Can you suggest where I might look next to figure out what the issue might be? I'm not particularly aware of CRIU related configurations.

Thanks :)

**Comment by YJDoc2** [comment]
It is likely some issue with the system setup on our side
>It is strange as it works in CI and on my system.

It is 1, maybe that is the issue, but I tried changing it using `sudo echo "0" | sudo tee /proc...` and even after its changed, it still does not pass the tests, fails with same error
> What is the value of /proc/sys/kernel/yama/ptrace_scope? That should be 0.

Yes, I am running it as root
> Are you running the test as root?

Thanks for this, I'll be trying this to see exactly where the error is getting generates, and report back :+1:
> What I did during development is to make youki point to a local copy of the rust-criu crate using file paths instead of an URL to github. That way I was able to insert print statements.

**Comment by YJDoc2** [comment]
Hey @adrianreber as I expected it was an issue with my system setup : particularly, I had not installed criu binary :sweat_smile: :sweat_smile:  
Apologies for the confusion :sweat: 
@utam0k can you check if you have the same issue? If so, then we must add `criu` as a dependency in the installation instruction in Readme and docs.

That said, now there is another issue that is occurring : the checkpoint and leave running test is passing for youki but failing for runc. The reason is `dump.log` file is not found. I checked the `/tmp/container_id/checkpoint ` dir, and it contains `.img` files, and `descriptors.json` but not the `dump.log` file.

**Comment by adrianreber** [comment]
Do you have runc 1.1.0? runc changed its checkpoint behavior in 1.1.0 and I followed runc 1.1.0 for the youki implementation.

**Comment by YJDoc2** [comment]
Hey, so my distribution had 1.0.3, which is why the issue was happening. I have tested on 1.1.0 and it works perfectly.

Thanks for all the help, and apologies for the confusion caused  just because of my setup issues :sweat: :sweat: 

If @utam0k 's issue was due to the same reason, I will open a PR and update the Readme to mention these requirements, and then we can close this issue.

Thanks :)

**Comment by adrianreber** [comment]
> I had not installed criu binary 

Maybe we should provide a better error message if the binary is missing at some level of the stack.

**Comment by YJDoc2** [comment]
I was thinking the same thing. Along with the binary other errors are also reported as-are which can benefit from additional context information, especially when trying to locate where exactly the error is occurring. I have opened  https://github.com/checkpoint-restore/rust-criu/issues/1 , if that is fine, I would work on adding context messages to the errors that are propagated from the library to its users.
> Maybe we should provide a better error message if the binary is missing at some level of the stack.

**Comment by YJDoc2** [comment]
@utam0k can you confirm if you had the same issue or not? My PR for updating error messages in rust-criu has been merged, so if you had the same issue, then with a PR here updating the Readme to add criu binary as dependency for dev  we can close this issue. Else we'll need to further investigate if  you are still having the issue.

**Comment by utam0k** [comment]
@YJDoc2 Can I ask you to give me some commands to install it?

**Comment by YJDoc2** [comment]
Hey @utam0k I use Ubuntu, so I just did `sudo apt-get update && sudo apt-get install criu`
Also, I have updated the error messages in the rust-criu library. Can you try updating the git dependency to latest commit and then running test, so you might get a better error message to understand what exactly is going wrong?
Thanks :)

**Comment by YJDoc2** [comment]
@utam0k it is possible , I tried digging through the source, and this is where the error originates in criu C source : https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/net.c#L643

Checking through the device numbers and stuff, I guess wsl2 uses host ip to create a tunnel to running Linux kernel, and connect to it, however when running criu , it does not support ipip (ip in ip tunnel) kind of device , and thus gives an error when mounting the network cgroup system (?)

**Comment by YJDoc2** [comment]
I am using native Linux system, and the tests seem to work fine for me

**Comment by utam0k** [comment]
@YJDoc2 Thanks!! In the case of wsl2, should we skip the test and just walk away for once?

**Comment by YJDoc2** [comment]
Closing, as the main issue was not really related to youki itself, more of a dependency/setup issue.
And yes, maybe we should walk away this time :smile:
