### ISSUE TITLE
Integration tests should be part of the `cargo` workspace

### ISSUE THREAD

**Issue by adoerr** [containers/youki#838]
Currently the workspace virtual manifest is located in `./crates` and workspace members are the crates below the `./crates` folder.

None of the integration test crates below `./tests/rust-integration-tests` are workspace members. This means that tools like `rust-analyzer` will basically ignore them. IMO, the whole codebase including the tests should be part of the workspace.

I'm also always a bit irritated if a Rust codebase doesn't have a `Cargo.toml` (with or without a workspace) at it's root.

Hence, I do suggest to move the virtual manifest from `./crates` to the project root and also add the directories below `./tests/rust-integration-tests` to the workspace. This will also result in a single `target` folder for both regular code and integration tests.

WDYT?

**Comment by YJDoc2** [comment]
Hey,

So the separation of integration tests from the youki crates was a deliberate decision, as the integration test binaries, specifically the `runtimetest` binary needs to be statically linked, unlike rest of binaries which are dynamically linked. This crates an issue, as then for each compilation, crates which both youki and tests depend on such as oci-spec are compiled twice , once for each linking-type even if it is not strictly necessary. Thus we have separated the integration tests altogether from the youki crates. This separation also provides a nice separation-of-cause (at least in my opinion) as the integration tests are not strictly youki-specific ; they are rust port of OCI tests, and thus should not be directly connected to youki crates.

As for this part, you might want to take a look at #820 , where it was discussed recently.
> I'm also always a bit irritated if a Rust codebase doesn't have a Cargo.toml (with or without a workspace) at it's root.

**Comment by adoerr** [comment]
Thanks for the feedback!

> Thus we have separated the integration tests altogether from the youki crates. This separation also provides a nice separation-of-cause (at least in my opinion) as the integration tests are not strictly youki-specific ; they are rust port of OCI tests, and thus should not be directly connected to youki crates.

Understood. You might want to consider moving the integration tests into a separate project / repo in order to make the separation explicit and obvious.

Anyways, fell free to close the issue.
