### ISSUE TITLE
.gitignore ignores `integration_test` files/directories

### ISSUE THREAD

**Issue by tony84727** [containers/youki#958]
Hello, 

AFAIK, there was a directory refactor for integration tests.

When editing the integration tests (under `tests/rust-integration-tests/integration_test`), git complains that the source code is ignored.
because:
https://github.com/containers/youki/blob/3644c008f1604f698f9b40a21f06f024a107cad7/.gitignore#L15

Is that intentional? Or should we update the `.gitignore`?

Edit:
Just realized that the rule was to ignore the `integration_test` executable.
Maybe we should prefix the rule with a slash, so git only ignores the name within the directory, where the `.gitignore` file lives in, instead of ignoring any path with `integration_test` inside it. (i.e. tests/rust-integration-tests/**integration_test**)

**Comment by utam0k** [comment]
@tony84727 That's right. I'd like to only ignore the `integration_test` executable file. Can I ask you to help us?

**Comment by tony84727** [comment]
Sure, this one should be easy. I will submit a PR later today (or maybe tomorrow)!
